### ISSUE TITLE
Redis database configuration not applied

### ISSUE THREAD

**Issue by flaushi** [doctrine/DoctrineBundle#1033]
I am configuring several redis cache services for doctrine. The `database` option is not applied, all connections are established with database 0 (also metadata and  query). 
Here is my doctrine.yaml
```
doctrine_cache:
    providers:
        slc:
            redis:
                host: '%env(REDIS_HOST)%'
                database: '%env(REDIS_DB)%'
            namespace: slc_ns
        metadata:
            redis:
                host: '%env(REDIS_HOST)%'
                database: '%env(REDIS_DB)%'
            namespace: metadata_ns
        query:
            redis:
                host: '%env(REDIS_HOST)%'
                database: '%env(REDIS_DB)%'
            namespace: query_ns
doctrine:
    orm:
       second_level_cache:
             regions:
                default:
                    lifetime: 0
                    cache_driver:
                        type: service
                        id: doctrine_cache.providers.slc
```

However, when defining a "standard" redis cache in the symfony framework config like
```
framework:
    cache:
        default_redis_provider: 'redis://%env(REDIS_HOST)%/%env(REDIS_DB)%'
        pools:
            tagged_data_cache:
                adapter: cache.adapter.redis
                default_lifetime: 0
                tags: true
```
this does work as it should and will respect the REDIS_DB setting.

Background: I have one test server that runs about 10 instances of my symfony app. There is one nginx with 10 available sites (one port for each app instance), and there is one postgresql server which has a database for each instance. Finally, the machine runs a redis server and each instance has it's own database index in .env.local, e.g. REDIS_DB="4" 

However, I regularly see strings from entities in one installation occurring in other apps. I also have a different APP_SECRET in each .env.local
