### ISSUE TITLE
Unknown cache of type "array" configured for cache 

### ISSUE THREAD

**Issue by alebedev80** [doctrine/DoctrineBundle#1060]
After switching to version 2.0 my configuration stop to work and i've got error:

`Unknown cache of type "array" configured for cache "metadata_cache" in entity manager "acp". ` 

```
#config/packages/dev/doctrine.yaml
doctrine:
    orm:
        entity_managers:
            acp:
                metadata_cache_driver: array
                query_cache_driver: array
                result_cache_driver: array
```
