### ISSUE TITLE
[Profiler] An error occurred while loading the query explanation

### ISSUE THREAD

**Issue by darthf1** [doctrine/DoctrineBundle#1152]
Hi! On the SF Profiler on the Doctrine tab, does not matter which request of which query, if I click on the link `Explain query` I get the message: `An error occurred while loading the query explanation.`

![image](https://user-images.githubusercontent.com/17253332/77151165-ac344700-6a95-11ea-961f-d9d4f54bd076.png)

![image](https://user-images.githubusercontent.com/17253332/77151183-b8200900-6a95-11ea-95cb-712750352efe.png)

Clicking on the link creates a new requests, which returns a 500 error:

![image](https://user-images.githubusercontent.com/17253332/77151487-53b17980-6a96-11ea-9339-bc0ccb99f648.png)

My config:
```
doctrine:
  dbal:
    # configure these for your database server
    driver: "pdo_pgsql"
    charset: utf8
    url: "%env(resolve:DATABASE_URL)%"
    logging: "%kernel.debug%"
    schema_filter: "~^(?!(messenger_messages|import))~"
    types:
      decimal:  App\DBAL\Types\DecimalType
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: "%kernel.project_dir%/src/Entity"
        prefix: 'App\Entity'
        alias: App
```
My connection string:
```
DATABASE_URL=postgres://xxx:xxx@db/xxx?serverVersion=11.7
```

My deps:
PHP 7.4.3
Symfony 5.0.5
Doctrine/ORM 2.7.1
PostgreSQL 11.7
