### ISSUE TITLE
[feedback] Removed the mysql charset hack for 5.3.6+ 

### ISSUE THREAD

**Issue by recipe** [doctrine/DoctrineBundle#116]
I need this piece of code to be working, because after @stof did the changes SET NAMES UTF8 is absent.
[Reference to commit](https://github.com/doctrine/DoctrineBundle/commit/f3e08513af97423bc713a62fe2bd9252d82852c6#commitcomment-1840296)

I have php 5.3.13.  Mysql Version 5.1.40-community

```
$ php --info | grep PDO
PDO
PDO support => enabled
PDO drivers => mysql, sqlite
PDO Driver for MySQL => enabled
PDO Driver for SQLite 3.x => enabled
```

config.yml

``` yaml
doctrine:
    dbal:
        connections:
            default:
                driver:   %database_driver%
                dbname:   %database_name%
                host:     %database_host%
                port:     %database_port%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
```
