### ISSUE TITLE
Dynamic connection parameters

### ISSUE THREAD

**Issue by Agares** [doctrine/DoctrineBundle#1178]
I need the ability to pass the hostname, database name and port dynamically (i.e. I don't know those until runtime). I'm happy to send a PR that would allow that, though I'd like to discuss the approach first.
There are two solutions that come to my mind:
1. Create a new option for DBAL that would allow passing a factory (a service from DI) and a method that would just return a DBAL connection.
2. Create an extension point that would allow dynamically generating the connection parameters, but would still use the current instantiation logic.

I'm open to other ideas (or maybe there's a way to do it with the bundle as it is right now that I missed?).

**Comment by ostrolucky** [comment]
There already is a connection factory in this bundle. What prevents you to use your own implementation?

**Comment by Agares** [comment]
The issue with replacing the bundle's connection factory, is that I would be limited to the configuration options, I cannot for example do something like this:
```
doctrine:
  dbal:
    connections:
      test_connection:
        my_database_identifier: 'My favourite database'
```

If I could pass a custom connection factory, e.g. like this:
```
doctrine:
  dbal:
    connections:
      test_connection:
        factory: ['my.wonderful.dbal_connection_factory', 'createConnectionToMyFavouriteDatabase']
```

Then I could do whatever I want in the service behind `my.wonderful.dbal_connection_factory`, without being limited by the options that the bundle allows
