### ISSUE TITLE
Inject custom orm mapping driver

### ISSUE THREAD

**Issue by KartaviK** [doctrine/DoctrineBundle#1193]
I cant find any docs or information about how to inject my own mapping driver to bundle. How it can be implemented
I want just configure it and set in config like that
```yaml
doctrine:
    ...
    dbal:
        ...
    orm:
        mappings:
            App:
                type: my_custom_dtiver
```
