### ISSUE TITLE
schema_filter is no more respected in 2.1.0

### ISSUE THREAD

**Issue by theravel** [doctrine/DoctrineBundle#1194]
Have doctrine configuration (`doctrine.yaml`)
```
parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                server_version: '5.7'
                host:     "%env(DB_HOST)%"
                port:     "%env(DB_PORT)%"
                dbname:   "%env(DB_NAME)%"
                user:     "%env(DB_USER)%"
                password: "%env(DB_PASSWORD)%"
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                schema_filter: '~^(?!system_)~'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```

Have messenger configuration (`messenger.yaml`)
```
framework:
    messenger:
        transports:
            doctrine_failed:
                dsn: '%env(MESSENGER_TRANSPORT_DOCTRINE_DSN)%'
                serializer: messenger.failed_messages_serializer
                options:
                    table_name: 'system_failed_messages'
                    auto_setup: false
        failure_transport: doctrine_failed
```

Execute `schema:update`, it does not return an error:
```
php bin/console doctrine:schema:update --dump-sql           
                                                                                                     
 [OK] No Metadata Classes to process.                                                                                   
```

Execute `schema:validate`, it returns an error:
```
php bin/console doctrine:schema:validate

Mapping
-------
                                                                                               
 [OK] The mapping files are correct.                                                                                                                                                                                                   

Database
--------
                                                                                                   
 [ERROR] The database schema is not in sync with the current mapping file.  
```

If you debug what exactly `schema:validate` does not like, it suggests to create `system_failed_messages` table.

Same configuration works perfectly fine in 2.0.8 (`schema:validate` does not return an error).
