### ISSUE TITLE
Console Commands: Possible bug - Using MasterSlaveConnection does not respect driverOptions

### ISSUE THREAD

**Issue by petewalker** [doctrine/DoctrineBundle#1230]
We're using `MasterSlaveConnection` to allow us to make use of read replicas in production.

I'm trying to set up an SSL certificate with the connections as we'd like to enforce TLS on our connections. I'm using the below config:

```yaml
doctrine:
  dbal:
    driver: pdo_mysql
    host: "%env(DATABASE_WRITER_HOST)%"
    port: "%env(DATABASE_WRITER_PORT)%"
    dbname: "%env(DATABASE_NAME)%"
    user: "%env(DATABASE_USER)%"
    password: "%env(DATABASE_PASSWORD)%"
    slaves:
      slave1:
        host: "%env(DATABASE_READER_HOST)%"
        port: "%env(DATABASE_READER_PORT)%"
        dbname: "%env(DATABASE_NAME)%"
        user: "%env(DATABASE_USER)%"
        password: "%env(DATABASE_PASSWORD)%"
    options:
      !php/const:PDO::MYSQL_ATTR_SSL_CA: "%kernel.project_dir%/certs/ca.crt"
```

Symfony responds to this config fine, and a TLS connection seems to be established with the MySQL server. However, when I try to run a CLI command:

```sh
bin/console doctrine:database:drop --force --env test

In AbstractMySQLDriver.php line 106:
                                                                                                                       
  An exception occurred in driver: SQLSTATE[HY000] [3159] Connections using insecure transport are prohibited while -  
  -require_secure_transport=ON.  
```

When I inspect what's going on in the command:

```php
$params = $connection->getParams();
if (isset($params['master'])) {
    $params = $params['master'];
}
// Yields
/*
array(6) {
  ["host"]=>
  string(9) "op_api_db"
  ["port"]=>
  string(4) "3306"
  ["dbname"]=>
  string(14) "local"
  ["user"]=>
  string(4) "root"
  ["password"]=>
  string(12) "insecurepass"
  ["driver"]=>
  string(9) "pdo_mysql"
}
*/
```

The `driverOptions` key is present in the initial `$params` array, but is then lost by this condition. If I replace with:

```php
$params = $connection->getParams();
$driverOptions = $params['driverOptions'] ?? [];
if (isset($params['master'])) {
    $params = $params['master'];
}
$params['driverOptions'] = $driverOptions;
```

It works. Is this a bug, or have I misconfigured?
