### ISSUE TITLE
Config parameter "logging" didn't work with parameters passed via env

### ISSUE THREAD

**Issue by FallDi** [doctrine/DoctrineBundle#1244]
```
# config/services.yaml
parameters:
     log_sql_queries: '%env(bool:LOG_SQL_QUERIES)%'
```

```
# .env
LOG_SQL_QUERIES=0
````

```
# config/packages/doctrine.yaml
doctrine:
    dbal:
        logging: '%log_sql_queries%'
```

Actual result: queries are logged
Expected result: queries are NOT logged

Root cause:
https://github.com/doctrine/DoctrineBundle/blob/6b1620354863f1f04fd4aa0a725e4ad1c728faac/DependencyInjection/DoctrineExtension.php#L139
`$connection['logging']` contains something like `string(74) "env_53d7fe31b9ea8cf5_bool_LOG_SQL_QUERIES_d2a427ed60021c1b934ed0f420ebe859"`
