### ISSUE TITLE
schema_filter is no more respected in combination with symfony/doctrine-messenger

### ISSUE THREAD

**Issue by theravel** [doctrine/DoctrineBundle#1289]
I will re-iterate issue described in https://github.com/doctrine/DoctrineBundle/issues/1194

I am now not sure if issue belongs to doctrine bundle, so please redirect me if needed.

Have doctrine configuration (`doctrine.yaml`)
```
parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                server_version: '5.7'
                host:     "%env(DB_HOST)%"
                port:     "%env(DB_PORT)%"
                dbname:   "%env(DB_NAME)%"
                user:     "%env(DB_USER)%"
                password: "%env(DB_PASSWORD)%"
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                schema_filter: '~^(?!system_)~'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```

Have messenger configuration (`messenger.yaml`)
```
framework:
    messenger:
        transports:
            doctrine_failed:
                dsn: '%env(MESSENGER_TRANSPORT_DOCTRINE_DSN)%'
                serializer: messenger.failed_messages_serializer
                options:
                    table_name: 'system_failed_messages'
                    auto_setup: false
        failure_transport: doctrine_failed
```

Execute `schema:update`, it does not return an error:
```
php bin/console doctrine:schema:update --dump-sql           
                                                                                                     
 [OK] No Metadata Classes to process.                                                                                   
```

Execute `schema:validate`, it returns an error:
```
php bin/console doctrine:schema:validate

Mapping
-------
                                                                                               
 [OK] The mapping files are correct.                                                                                                                                                                                                   

Database
--------
                                                                                                   
 [ERROR] The database schema is not in sync with the current mapping file.  
```

If you debug what exactly `schema:validate` does not like, it suggests to create `system_failed_messages` table.

What happens in more details:
1) We go to https://github.com/doctrine/orm/blob/v2.7.3/lib/Doctrine/ORM/Tools/SchemaValidator.php#L271
2) Then to https://github.com/doctrine/orm/blob/v2.7.3/lib/Doctrine/ORM/Tools/SchemaTool.php#L895
3) Then to https://github.com/doctrine/orm/blob/v2.7.3/lib/Doctrine/ORM/Tools/SchemaTool.php#L361-L366
4) Then to listener, where table is added to schema https://github.com/symfony/doctrine-bridge/blob/v5.2.3/SchemaListener/MessengerTransportDoctrineSchemaSubscriber.php#L41-L50
5) And then here we get `$toSchema` with messenger failed transport table declared https://github.com/doctrine/orm/blob/v2.7.3/lib/Doctrine/ORM/Tools/SchemaTool.php#L895
6) Which is not filtered out by `schema_filter`, so `doctrine:schema:validate` fails
Expected result from my PoV: `schema_filter` should be respected 

Why `doctrine:schema:update --dump-sql` returns other output for me? Because I get into this block of code https://github.com/doctrine/orm/blob/v2.7.3/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/AbstractCommand.php#L65
