### ISSUE TITLE
Not setting doctrine.dbal.override_url to true is deprecated. True is the only value that will be supported in doctrine-bundle 3.0.

### ISSUE THREAD

**Issue by ruudk** [doctrine/DoctrineBundle#1329]
When upgrading to 2.3.1 I get this deprecation:
```
Not setting doctrine.dbal.override_url to true is deprecated. True is the only value that will be supported in doctrine-bundle 3.0.
```

When I add:
```yaml
doctrine:
    dbal:
        override_url: true
```
I get 
```
  Unrecognized option "override_url" under "doctrine.dbal". Available options are "connections", "default_connection", "types".
```

Adding it to the `connections` block doesn't solve the deprecation either:
```yaml
doctrine:
    dbal:
        connections:
            override_url: true
```

This is introduced in https://github.com/doctrine/DoctrineBundle/pull/1290

**Comment by ruudk** [comment]
@jrushlow How to solve?

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/recipes/pull/900 and https://github.com/doctrine/DoctrineBundle/pull/1328

Closing as there is nothing to keep track of.

**Comment by ruudk** [comment]
Ok, so best to wait for another release? Because it's not possible to use 2.3.1 without having the deprecation?

**Comment by nicolas-grekas** [comment]
This removes the deprecation (as the message suggests):
```yaml
doctrine:
    dbal:
        override_url: true
```
