### ISSUE TITLE
type: service caches are broken in 2.4

### ISSUE THREAD

**Issue by alexander-schranz** [doctrine/DoctrineBundle#1348]
I currently did test @sulu against current `dev` dependencies and we have the following configured in the `prod/doctrine.yaml`:

<details>

<summary>doctrine.yaml</summary>

```yaml
doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: service
            id: doctrine.system_cache_provider
        query_cache_driver:
            type: service
            id: doctrine.system_cache_provider
        result_cache_driver:
            type: service
            id: doctrine.result_cache_provider

services:
    doctrine.result_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.result_cache_pool'
    doctrine.system_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.system_cache_pool'

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
```

</details>

> You have requested a non-existent service "doctrine.system_cache_provider".  

https://github.com/sulu/sulu/runs/2620361693

I think maybe there was a bc break introduced in the current current dev version, so I thought I will report this here. Updating the `doctrine.yaml` to something newer like this did fix it for us:

<details>

<summary>doctrine.yaml</summary>

```yaml
doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
```

</details>

So its not an issue for us currently as we did update the skeleton some time ago just thought I would report it that there was unexpected change which could maybe crash older projects an older cache configuration.
