### ISSUE TITLE
Either explicitly define DBAL connections error with version 2.4.1

### ISSUE THREAD

**Issue by ph-il** [doctrine/DoctrineBundle#1362]
Got "Either explicitly define DBAL connections in all doctrine-bundle configuration files, or in none of them." But looking at the changelog for 2.4.x I don't see anything that need to be change.

```
doctrine:
  dbal:
    default_connection:    default
    connections:
      default:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4
        server_version: '5.7'
        default_table_options:
          collate: utf8mb4_unicode_ci
```

**Comment by ostrolucky** [comment]
Look in all files. Have you checked prod/doctrine.yaml?

**Comment by ph-il** [comment]
I was in dev, no other file. And Prod : 

```

doctrine:
  orm:
    auto_generate_proxy_classes: false
    metadata_cache_driver: pool
    #            type: service
    #            id: doctrine.system_cache_provider
    query_cache_driver: pool
    #            type: service
    #            id: doctrine.system_cache_provider
    result_cache_driver: pool
#            type: service
#            id: doctrine.result_cache_provider


```
