### ISSUE TITLE
second level cache is broken

### ISSUE THREAD

**Issue by Ne-Lexa** [doctrine/DoctrineBundle#1364]
**DoctrineBundle affected**: 2.4.1

**Description**
After the `сomposer update` and updates `doctrine/doctrine-bundles` to 2.4, there is a fatal error.  
Before updating the error package was not.

**How to reproduce**
```yaml
// config/packages/cache.yaml
framework:
    cache:
        # Redis
        app: cache.adapter.redis_tag_aware
        default_redis_provider: redis://localhost
```

```yaml
// config/packages/doctrine_second_cache.yaml
doctrine:
    orm:
        second_level_cache:
            enabled: true
            region_cache_driver:
                type: pool
                pool: doctrine.second_level_cache_pool

framework:
    cache:
        pools:
            doctrine.second_level_cache_pool:
                adapter:          cache.app
                default_lifetime: 60
```

**Additional context**
```bash
$ bin/console cache:clear
TypeError {#568
  #message: "Argument 2 passed to Doctrine\ORM\Cache\DefaultCacheFactory::__construct() must implement interface Doctrine\Common\Cache\Cache, instance of Symfony\Component\Cache\Adapter\TraceableTagAwareAdapter given, called in /tmp/sf5.2/var/cache/dev/ContainerVpzExal/App_KernelDevDebugContainer.php on line 665"
  #code: 0
  #file: "./vendor/doctrine/orm/lib/Doctrine/ORM/Cache/DefaultCacheFactory.php"
  #line: 65
  trace: {
    ./vendor/doctrine/orm/lib/Doctrine/ORM/Cache/DefaultCacheFactory.php:65 { …}
    ./var/cache/dev/ContainerVpzExal/App_KernelDevDebugContainer.php:665 {
      ContainerVpzExal\App_KernelDevDebugContainer->getDoctrine_Orm_DefaultEntityManagerService($lazyLoad = true)^
      › $b->setCacheLogger($c);
      › $b->setCacheFactory(new \Doctrine\ORM\Cache\DefaultCacheFactory($d, ($this->privates['doctrine.second_level_cache_pool'] ?? $this->getDoctrine_SecondLevelCachePoolService())));
      › $b->setRegionsConfiguration($d);
    }
    ./var/cache/dev/ContainerVpzExal/App_KernelDevDebugContainer.php:612 { …}
    ./var/cache/dev/ContainerVpzExal/EntityManager_9a5be93.php:239 { …}
    ./var/cache/dev/ContainerVpzExal/EntityManager_9a5be93.php:239 { …}
    ./vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php:54 { …}
    ./vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:98 { …}
    ./vendor/symfony/http-kernel/Kernel.php:580 { …}
    ./vendor/symfony/http-kernel/Kernel.php:780 { …}
    ./vendor/symfony/http-kernel/Kernel.php:121 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:168 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:74 { …}
    ./vendor/symfony/console/Application.php:166 { …}
    ./bin/console:43 { …}
  }
}
2021-06-01T20:38:15+00:00 [critical] Uncaught Error: Argument 2 passed to Doctrine\ORM\Cache\DefaultCacheFactory::__construct() must implement interface Doctrine\Common\Cache\Cache, instance of Symfony\Component\Cache\Adapter\TraceableTagAwareAdapter given, called in /tmp/sf5.2/var/cache/dev/ContainerVpzExal/App_KernelDevDebugContainer.php on line 665
```

**Comment by alcaeus** [comment]
I've managed to reproduce this and will have a fix shortly.

**Comment by alcaeus** [comment]
@Ne-Lexa can you please check if #1365 fixes this issue for you? Thanks!

**Comment by Ne-Lexa** [comment]
Yes, I installed the version `2.4.x-dev#bc6fc27dda3c8edad6189298e9a7eb7c99c87d55` and the error disappeared.  
When can I expect a release version 2.4.2?
Thanks.

**Comment by alcaeus** [comment]
Thanks for confirming it works!

**Comment by gtgt** [comment]
I did the following workaround (we have policy to not use development versions): I've created a factory service (named: `doctrine.cache.second_level`) using the `Doctrine\Common\Cache\Psr6\DoctrineProvider::wrap` and the symfony cache pool `cache.doctrine.second_level` as the subject (which is originally created for second level cache).
```
# cache.yaml
framework:
    cache:
        # ...
        pools:
           # ...
            cache.doctrine.second_level:
                adapter: cache.app
                default_lifetime: 300
```
```
# doctrine.yaml
services:
    # remove service when this bugfix going into stable: https://github.com/doctrine/DoctrineBundle/pull/1365
    doctrine.cache.second_level:
        class: Psr\Cache\CacheItemPoolInterface
        factory: ['Doctrine\Common\Cache\Psr6\DoctrineProvider', 'wrap']
        arguments: ['@cache.doctrine.second_level']
doctrine:
    # ...
    orm:
        # ...
        second_level_cache:
            enabled: true
            region_lifetime: 300
            region_cache_driver:
                type: pool
                # revert back when this bugfix going into stable: https://github.com/doctrine/DoctrineBundle/pull/1365
                pool: doctrine.cache.second_level
                #pool: cache.doctrine.second_level
```
All can be reverted back with the release of 2.4.2, however it should work even after.

**Comment by dkarlovi** [comment]
Thanks @alcaeus for fixing it, but also thank you @Ne-Lexa for reporting it, I was just about to and you saved me some work there!  :heart:

**Comment by alcaeus** [comment]
We'll have 2.4.2 out soon. It's a holiday, so you'll have to excuse me spending the day in the sun. Thanks for all the positivity here, we appreciate it!

**Comment by cybernet** [comment]
when can you release the fix ?

**Comment by ThomasTr** [comment]
Hmmm, with this config
````
framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name
        prefix_seed: app

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:
        app: cache.adapter.redis
        system: cache.adapter.system

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost
        default_redis_provider: '%env(REDIS_PROVIDER)%'

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        #pools:
            #my.dedicated.cache: null
        pools:
            app.cache.redis:
                adapter: cache.adapter.redis
            doctrine.result_cache_pool:
                adapter: app.cache.redis
            doctrine.system_cache_pool:
                adapter: app.cache.redis
````

````
doctrine:
    orm:
        auto_generate_proxy_classes: false
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool
        second_level_cache:
            enabled: true
            regions:
                lifelong:
                    lifetime: 0
                    cache_driver:
                        type: pool
                        pool: app.cache.redis
````
Update from 2.3.2 to 2.4.2 fails for me with the exact same error:
````

Uncaught Error: Doctrine\ORM\Cache\Region\DefaultRegion::__construct(): Argument #2 ($cache) must be of type Doctrine\Common\Cache\Cache, Symfony\Component\Cache\Adapter\TraceableAdapter given, called in /projects/var/cache/dev/ContainerTMxxJlQ/App_KernelDevDebugContainer.php                                                                   
````

**Comment by alcaeus** [comment]
Thanks for providing the config. We'll investigate this.

**Comment by Khartir** [comment]
We have the same issue as @ThomasTr with a similar config. Should we open a new issue or will this one be reopened?

**Comment by alcaeus** [comment]
@ThomasTr, @Khartir: if you're able to reproduce this issue, could you please create a PR to add the failing config as a test? The tests added in #1365 can serve as guidance, and after adding the appropriate config to the configuration files (both [XML](https://github.com/doctrine/DoctrineBundle/blob/4202ce675d29e70a8b9ee763bec021b6f44caccb/Tests/DependencyInjection/Fixtures/config/xml/orm_caches.xml) and [YAML](https://github.com/doctrine/DoctrineBundle/blob/4202ce675d29e70a8b9ee763bec021b6f44caccb/Tests/DependencyInjection/Fixtures/config/xml/orm_caches.yml) config files need to be updated) you can add it to the [data provider](https://github.com/doctrine/DoctrineBundle/blob/4202ce675d29e70a8b9ee763bec021b6f44caccb/Tests/DependencyInjection/AbstractDoctrineExtensionTest.php#L718).

Thanks for helping out!

**Comment by ostrolucky** [comment]
I've already fiddled with this, testcase looks like this
```patch
Index: Tests/DependencyInjection/Compiler/CacheCompatibilityPassTest.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Tests/DependencyInjection/Compiler/CacheCompatibilityPassTest.php b/Tests/DependencyInjection/Compiler/CacheCompatibilityPassTest.php
--- a/Tests/DependencyInjection/Compiler/CacheCompatibilityPassTest.php	(revision 4202ce675d29e70a8b9ee763bec021b6f44caccb)
+++ b/Tests/DependencyInjection/Compiler/CacheCompatibilityPassTest.php	(date 1624392152242)
@@ -36,6 +36,12 @@
                             'orm' => [
                                 'query_cache_driver' => ['type' => 'service', 'id' => 'custom_cache_service'],
                                 'result_cache_driver' => ['type' => 'pool', 'pool' => 'doctrine.system_cache_pool'],
+                                'second_level_cache' => [
+                                    'enabled' => true,
+                                    'regions' => [
+                                        'lifelong' => ['lifetime' => 0, 'cache_driver' => ['type' => 'pool', 'pool' => 'doctrine.system_cache_pool']],
+                                    ],
+                                ],
                             ],
                         ]
                     );

```

It's not an easy fix though, because our compiler pass relies on Aliases and these don't exist for this case. So I postponed fixing this myself until who knows when.

**Comment by ostrolucky** [comment]
In case someone would like to try, there is a fix at https://github.com/doctrine/DoctrineBundle/pull/1397

**Comment by biozshock** [comment]
@ostrolucky the issue is still present when using `type: filelock`

```yaml
cache_lifetime:
  type: filelock
  lock_lifetime: 2
  lock_path: '%kernel.cache_dir%/doctrine'
  cache_driver:
    type: pool
    pool: cache.cache_store
```
