### ISSUE TITLE
Unrecognized option "connections" under "doctrine.dbal.connections.default" after composer update

### ISSUE THREAD

**Issue by facundososalopez** [doctrine/DoctrineBundle#1366]
- Upgrading doctrine/doctrine-bundle (2.3.2 => 2.4.1)
- Upgrading doctrine/orm (2.9.1 => 2.9.2)

Configuration:

```yaml
doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```
