### ISSUE TITLE
resolve_target_entities doesn't work with custom mapping dir

### ISSUE THREAD

**Issue by mvrhov** [doctrine/DoctrineBundle#137]
``` yaml
        resolve_target_entities: #just to make doctrine happy
            Foo\Bundle\AssetBundle\Model\Label: Label
        entity_managers:
            default:
                mappings:
                    FooAccountBundle:
                        prefix: Foo\Bundle\AccountBundle\Model
                        dir: Resources/config/doctrine/dep
```

When warming up the cache I'm getting
[Doctrine\Common\Persistence\Mapping\MappingException]
No mapping file found named 'Foo/Bundle/AccountBundle/Resources/config/doctrine/Label.orm.xml' for class 'Foo\Bundle\AccountBundle\Model\Label'. Which is clearly wrong as I have configured the mapping dir to be in doctrine/dep
