### ISSUE TITLE
default_second_level_cache.region_cache_driver does not exist. after 2.9

### ISSUE THREAD

**Issue by SacreDPamiR** [doctrine/DoctrineBundle#1375]
After updating, I am having an error due to a setting configuration that I do not understand. Does anyone else have this problem? were you able to find any solution?

`The service alias "doctrine.orm.default_second_level_cache.region_cache_driver" does not exist.`

**Comment by alcaeus** [comment]
Please post a minimal example of a config that reproduces this. While the service name internally may have changed, the bundle should not be using old names when injecting services. If you are using the service in your own config, please don't as this service is very much internal to Doctrine and you shouldn't be working with it at all.

**Comment by SacreDPamiR** [comment]
My doctrine config
```
orm:
        auto_generate_proxy_classes: false

        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        second_level_cache:
            enabled: true
            region_lifetime: 86400
            region_cache_driver:
                type: service
                id: snc_second_level_cache

        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```
And redis config

```
    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default
            namespace: 'dmc:'
        result_cache:
            client: doctrine
            entity_manager: default
            namespace: 'drc:'
        query_cache:
            client: doctrine
            entity_manager: default
            namespace: 'dqc:'
        second_level_cache:
            client: doctrine
            entity_manager: default
            namespace: 'dslc:'
```

(alcaeus: edited for formatting)
