### ISSUE TITLE
"doctrine.orm.default_metadata_cache" does not exist

### ISSUE THREAD

**Issue by ghost** [doctrine/DoctrineBundle#1376]
I've searched for a long time for the source of this problem as the error message appears in DependencyInjection\ContainerBuilder anywhere in the code.

Well I found out that the DoctrineExtension of this Bundle is doing something with that.

That problem occurred after upgrading Symfony from 4.1 to 4.4
I hope we can fix this somehow.

**Comment by alcaeus** [comment]
Please post a minimal example of a config that reproduces this. While the service name internally may have changed, the bundle should not be using old names when injecting services. If you are using the service in your own config, please don't as this service is very much internal to Doctrine and you shouldn't be working with it at all.

**Comment by ghost** [comment]
I haven't changed any config, I don't even have a metadata_cache service defined in doctrine.
And also if I define a valid one it breaks with that message.

The Symfony upgrade forced me to use v2.4.2 instead of v1.9.x

Example config:
```
doctrine:
    orm:
        metadata_cache_driver:
          type: service
          id: Predis\Client
        query_cache_driver:
          type: service
          id: Predis\Client
        result_cache_driver:
          type: service
          id: Predis\Client
```
