### ISSUE TITLE
PHP 8.0 annotations mapping issues

### ISSUE THREAD

**Issue by alex-bacart** [doctrine/DoctrineBundle#1386]
New PHP 8.0 annotation syntax doesn't work in Symfony 5.3.

**Steps to reproduce**
1. Install new Symfony 5.3 project `symfony new --full my_project`
2. Create User entity
```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class User
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    public ?int $id = null;
}
```

3. Check the mapping info `bin/console doctrine:mapping:info`. Everything is ok
```
Found 1 mapped entities:
[OK]   App\Entity\User
```

4. Change an entity class annotation to a new syntax
```php
#[ORM\Entity]
class User
```

5. Check the mapping info `bin/console doctrine:mapping:info`. An error occurs
```
 !
 ! [CAUTION] You do not have any mapped Doctrine ORM entities according to the current configuration.
 !
 !           If you have entities or mapping files you should check your mapping configuration for errors.
 !
```

6. Restore an entity class annotation to the old syntax and change `$id` property annotation
```php
#[ORM\Id()]
#[ORM\GeneratedValue()]
#[ORM\Column("integer")]
public ?int $id = null;
```

7. Check the mapping info `bin/console doctrine:mapping:info`. An error occurs
```
Found 1 mapped entities:

[FAIL] App\Entity\User
No identifier/primary key specified for Entity "App\Entity\User". Every Entity must have an identifier/primary key.
```

**Comment by ostrolucky** [comment]
That's not enough. You need to specify different driver than annotation in config.

**Comment by rbnzdave** [comment]
As this still comes up in searches and the answer was vague,

in your doctrine.yaml config file, you need to change the type from Annotation to Attribute.

```
  orm:
    default_entity_manager: default
    entity_managers:
      default:
        connection: default
        mappings:
          Main:
            is_bundle: false
            **type: attribute**
            dir: '%kernel.project_dir%/src/Entity/Main'
            prefix: 'App\Entity\Main'
            alias: Main

```
