### ISSUE TITLE
Class "App\Cart\CartRepository" sub class of "Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository" is not a valid entity or mapped super class.

### ISSUE THREAD

**Issue by webgrig** [doctrine/DoctrineBundle#1390]
There is an entity Cart which is configured as follows

```
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Cart:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Cart'
                prefix: 'App\Cart'
                alias: Cart

```
Also, this entity has repository whose file is located in the same folder as the entity itself

```
namespace App\Cart;


use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * @method Cart|null find($id, $lockMode = null, $lockVersion = null)
 * @method Cart|null findOneBy(array $criteria, array $orderBy = null)
 * @method Cart[]    findAll()
 * @method Cart[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class CartRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Cart::class);
    }
}

```

But with this configuration I am getting browser exceptions
`
Class "App\Cart\CartRepository" sub class of "Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository" is not a valid entity or mapped super class.`

What is wrong and how to fix the situation?
