### ISSUE TITLE
Add SQLFilter parameter in the configuration for Doctrine ORM

### ISSUE THREAD

**Issue by yoannch** [doctrine/DoctrineBundle#14]
Hello there,

In doctrine 2.2, a new feature was added : sql filters made by @asm89 => https://github.com/doctrine/doctrine2/pull/210.

But the doctrinebundle seems not to enable this in the configuration, so I'd like to add it.

Maybe we could add it as follow, in the config.yml :

``` yaml
doctrine:

    orm:
        filters:
            my_first_filter:
                class: 'Fully\Qualified\Class\Name'
                enabled: true
            my_second_filter:
                class: 'Fully\Qualified\Class\Name2'
                enabled: true
```

and so modify the Configuration and DoctrineExtension classes to enable this?

What do you think about this?
