### ISSUE TITLE
v2.4.3 breaks SLC configurations based on services

### ISSUE THREAD

**Issue by Philosoft** [doctrine/DoctrineBundle#1414]
Commit which introduced the problem: https://github.com/doctrine/DoctrineBundle/commit/64234c75f49853e5619e98e9ed53493c3a3d85dc
Repository to reproduce: https://github.com/Philosoft/doctrine-bunle-slc-compiler-pass-bug

Basically you need just something like this

```yaml
doctrine:
    orm:
        second_level_cache:
            enabled: true
            log_enabled: true
            region_lock_lifetime: 600
            region_lifetime: 3600
            regions:
                entity_cache_region:
                    type: service
                    service: App\Doctrine\FileConcurrentRegion
                    lifetime: 6000
```
in your config

and then every attempt to clear cache in symfony (regenerate container) will fail with 

```
Script cache:clear returned with error code 1
!!
!!  In Definition.php line 321:
!!                                     
!!    The argument "1" doesn't exist.
```
