### ISSUE TITLE
Abnormal Doctrine behavior in a database with several schemas: 'unknown database type oid requested'

### ISSUE THREAD

**Issue by benruseau** [doctrine/DoctrineBundle#1423]
Hi :wave:, 

I'm working on a new Symfony project we started from scratch in my company, using the Doctrine ORM. 

Our project is connected to a PostgreSQL database which is already used by many other projects and where each project has its own dedicated schema. For this one, we created a schema named `offer_manager`. 

Here is our `doctrine.yaml` config file: 
```
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        schema_filter: /^(?!.*offer_manager).*/

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '11.2'
        driver:   pdo_pgsql
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```

And our `doctrine_migrations.yaml` file: 

```
doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: '%kernel.debug%'

    storage:
        table_storage:
            table_name: offer_manager.offer_migrations

```
But when we run `make:migration` command (from [Symfony maker bundle](https://github.com/symfony/maker-bundle)), we systematically get the following error: 

```
In AbstractPlatform.php line 398:
                                                                                                       
  Unknown database type oid requested, Doctrine\DBAL\Platforms\PostgreSQL100Platform may not support   
  it.                                                                                                        
```

We have searched for hours but we still can't figure out what we did wrong. We don't have any custom type `oid` anywhere (which actually seem to be a type used internally by [PostgreSQL](https://www.postgresql.org/docs/11/datatype-oid.html)). Or maybe there is a problem between Doctrine bundle and PostgreSQL? 

Here is our `composer.json` in case you would need it: 

```
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": "^8.0.11",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "composer/package-versions-deprecated": "1.11.99.4",
        "doctrine/annotations": "^1.0",
        "doctrine/doctrine-bundle": "^2.4",
        "doctrine/doctrine-migrations-bundle": "^3.2",
        "doctrine/orm": "^2.10",
        "nelmio/api-doc-bundle": "^4.6",
        "phpdocumentor/reflection-docblock": "^5.3",
        "stof/doctrine-extensions-bundle": "^1.6",
        "symfony/asset": "5.3.*",
        "symfony/console": "5.3.*",
        "symfony/doctrine-bridge": "5.3.*",
        "symfony/dotenv": "5.3.*",
        "symfony/flex": "^1.3.1",
        "symfony/framework-bundle": "5.3.*",
        "symfony/monolog-bundle": "^3.7",
        "symfony/property-access": "5.3.*",
        "symfony/property-info": "5.3.*",
        "symfony/proxy-manager-bridge": "5.3.*",
        "symfony/runtime": "5.3.*",
        "symfony/serializer": "5.3.*",
        "symfony/twig-bundle": "5.3.*",
        "symfony/uid": "5.3.*",
        "symfony/validator": "5.3.*",
        "symfony/yaml": "5.3.*"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "^3.1",
        "phpstan/extension-installer": "^1.0",
        "phpstan/phpstan": "^0.12.43",
        "phpstan/phpstan-beberlei-assert": "^0.12.3",
        "phpstan/phpstan-phpunit": "^0.12.16",
        "phpunit/phpunit": "^9.3",
        "symfony/browser-kit": "5.3.*",
        "symfony/maker-bundle": "^1.34"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*"
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "5.3.*"
        }
    }
}
```
Our PostgreSQL server version is `11.2`.

Thank you in advance for your help :pray:
