### ISSUE TITLE
Doesn't support memcache cache drivers using socket file and port 0 with Memcache class

### ISSUE THREAD

**Issue by tammyd** [doctrine/DoctrineBundle#145]
Using memcache with a socket file (ie setting memcache host to something like unix:/path/to/memcached.sock)  doesn't work. In order to use the \Memcache class in this way, the port specified has to be 0 (see [memcache.connect.php](http://php.net/manual/en/memcache.connect.php)). However, using port: 0 in the config.yml defaults back to 11211.

``` yml
doctrine:
    orm:
        result_cache_driver:
            type: memcache
            host: unix:/path/to/memcached.sock
            port: 0
            instance_class: Memcache
```

I can see this this in appDevDebugProjectContainer.php line 343 when trying to clear the cache.

``` php
protected function getDoctrine_Orm_DefaultMemcacheInstanceService()
{
    $this->services['doctrine.orm.default_memcache_instance'] = $instance = new \Memcache();

    $instance->connect('unix:/path/to/memcached.sock', 11211);

    return $instance;
}
```

Unfortunately, I have to use memcache in this way hosting a site on [Webfaction](http://docs.webfaction.com/software/memcached.html).
