### ISSUE TITLE
Configuration for collation in default table options (collate/collation)

### ISSUE THREAD

**Issue by aprat84** [doctrine/DoctrineBundle#1468]
In some places in this bundle and DBAL `collate` is used, in some other places `collation` is used. https://github.com/doctrine/dbal/issues/5214

I need to put both in my config:
```yaml
doctrine:
    dbal:
        default_table_options:
            charset: utf8mb4
            collation: utf8mb4_0900_ai_ci
            collate: utf8mb4_0900_ai_ci
```

If I only use `collate` (it worked before updating DBAL from 3.2.1 to 3.3.1), schema comparator, which uses `collation` config, detects changes and generates weird migrations when executing `doctrine:migrations:diff` command: empty `up()` and a `down()` full of useless ALTER TABLE.

If I only use `collation`, it creates new tables with `utf8mb4_unicode_ci` collation.

I know DBAL v4 won't force any charset/collation, but still the config documentation feels wrong...
https://github.com/doctrine/DoctrineBundle/blob/2.5.x/Resources/doc/configuration.rst

**Comment by greg0ire** [comment]
After https://github.com/doctrine/dbal/pull/5246 is released, this bundle should be modified to use either `collation` or `collate` depending on the version of the DBAL.

UPD: it just got released

**Comment by dmaicher** [comment]
@greg0ire @aprat84 I actually still have this issue on dbal 3.3.2

I'm using

```
default_table_options:
    collate: utf8_general_ci
```

I also tried

```
default_table_options:
    collation: utf8_general_ci
```

and 

```
default_table_options:
    collate: utf8_general_ci
    collation: utf8_general_ci
```

no luck. Always get those weird `down()` migrations like

```
ALTER TABLE address CHANGE street street LONGTEXT DEFAULT NULL COLLATE `utf8_unicode_ci`, ...
```

Is there a workaround?

**Comment by natewiebe13** [comment]
@dmaicher by updating dbal to 3.3.2 and changing the option from `collate` to `collation` (example 2 that you tried), I no longer get the weird migrations on down. Potentially there's another issue going on as well?

Here's my current dbal config:

```yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '8.0'
        driver: 'pdo_mysql'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collation: utf8mb4_unicode_ci
```

**Comment by dmaicher** [comment]
Ah it actually seems I'm using a mix of collations for different tables (some have `utf8_general_ci` and others `utf8_unicode_ci`) :confused: So somewhat the `down()` migrations are correct. However the  `up()` part is empty...

**Comment by floviolleau** [comment]
Hi,

We have the same issue on a project. We have a mix of `utf8_general_ci` and `utf8mb4_general_ci`.

We tried all different combinations and we still face to the issue in 3.3.2.

We rolled-back to 3.3.0 and it is working.

We spotted 
https://github.com/doctrine/dbal/milestone/108?closed=1

But the fix for 3.3.2 is not working for us

Any ideas?
Thanks

**Comment by aprat84** [comment]
With 3.3.2 there are no more weird migrations!

But, be aware: ConnectionFactory will configure both connection charset (utf8mb4) and, on MySQL/MariaDB,  `defaultTableOptions.collate` (utf8mb4_unicode_ci) if they don't exist. [ConnectionFactory.php:78](https://github.com/doctrine/DoctrineBundle/blob/5c086cbbe5327937dd6f90da075f7d421b0f28bc/ConnectionFactory.php#L78)

With the recent changes in DBAL 3.3.2, `collate` takes precedence over `collation`, so new tables are created with collation generated by ConnectionFactory (utf8mb4_unicode_ci) instead of what I have in `defaultTableOptions` (utf8mb4_0900_ai_ci).

So, for me, `doctrine.dbal.charset` and `doctrine.dbal.default_table_options.collation` are both mandatory:
```yaml
doctrine:
    dbal:
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collation: utf8mb4_0900_ai_ci
            engine: InnoDB
```

Maybe a quick fix would be to check for both names:
```php
if (!isset($params['defaultTableOptions']['collate']) && !isset($params['defaultTableOptions']['collation'])) {
    $params['defaultTableOptions']['collate'] = 'utf8mb4_unicode_ci';
}
```

And in the future, with DBAL v4, get rid of it.
