### ISSUE TITLE
Console commands do not respect dbname_suffix when replica configuration is used

### ISSUE THREAD

**Issue by kschusternetformic** [doctrine/DoctrineBundle#1469]
When running tests, the `dbname_suffix` is being ignored in the `test/doctrine.yaml` when a replica is set up. I have tried setting this options in the replica section in the `test/doctrine.yaml`, tried to reset the replica in the test environment, all with no effect.

Main `doctrine.yaml`:
```
doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        url: '%env(resolve:DATABASE_URL_WRITER)%'
        server_version: '13.4'
        driver: pdo_pgsql
        replicas:
          replica1:
            url: '%env(DATABASE_URL_READER)%'
```

`test/doctrine.yaml`:
```
doctrine:
    dbal:
        connections:
          default:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
```
