### ISSUE TITLE
[2.6] Error on default connection configuration where no logger was available

### ISSUE THREAD

**Issue by loic425** [doctrine/DoctrineBundle#1501]
When no using any logger, I have this following error

`The service "doctrine.dbal.default_connection.configuration" has a dependency on a non-existent service "Psr \Log\NullLogger".`

**Comment by ostrolucky** [comment]
What's your doctrine.yaml config?

**Comment by loic425** [comment]
@ostrolucky https://github.com/Sylius/SyliusResourceBundle/blob/master/src/Bundle/test/config/packages/doctrine.yaml

**Comment by loic425** [comment]
@ostrolucky 
If you want to test in on the bundle:

```bash
$ composer update
$ (cd src/Component && composer update)
$ (cd src/Bundle/test && bin/console cache:clear)
```

**Comment by ostrolucky** [comment]
maybe that's because logging: true by default

**Comment by loic425** [comment]
> maybe that's because logging: true by default

I just tried this, and I got the same error.
```yaml
doctrine:
    dbal:
        # [...]
        logging: false
```

**Comment by dmaicher** [comment]
This is due to https://github.com/Sylius/SyliusResourceBundle/blob/master/src/Bundle/test/config/services.yaml#L14

Not sure where the service with id `Psr\Log\NullLogger` is supposed to be defined?

Changing to

```diff
 services:
     # Gets rid of "[error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException"
     # errors in PHPUnit output when testing 404 errors.
-    logger: "@Psr\Log\NullLogger"
+    logger:
+        class: Psr\Log\NullLogger
 
     # Default configuration for services in *this* file
     _defaults:
```

should fix it. Or remove that definition entirely.

**Comment by dmaicher** [comment]
Closing as I don't see that this is caused by DoctrineBundle. Let us know if you still have issues.

**Comment by loic425** [comment]
@dmaicher I fixed it. Thank you a lot for your time.

```yaml
services:
    # Gets rid of "[error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException"
    # errors in PHPUnit output when testing 404 errors.
    Psr\Log\NullLogger: ~
    logger: '@Psr\Log\NullLogger'
```
