### ISSUE TITLE
Define custom ORM/DBAL settings in bundles

### ISSUE THREAD

**Issue by dlsniper** [doctrine/DoctrineBundle#153]
Hello,

I'm trying to define the following in my bundle (not in app/config/config.yml)

``` yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
```

but it seems it's failing with

```
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]                                                                                                                                                  
  There is no extension able to load the configuration for "doctrine" 
```

Any ideas?
