### ISSUE TITLE
[doc] Registering the entity listener on the entity is still required

### ISSUE THREAD

**Issue by stollr** [doctrine/DoctrineBundle#1548]
In the [documentation](https://symfony.com/bundles/DoctrineBundle/2.7.x/entity-listeners.html) it's said that

> Starting with doctrine/orm 2.5 and Doctrine bundle 1.5.2, instead of registering the entity listener on the entity, you can declare all options from the service definition

I have installed doctrine/orm 2.12.3 and Doctrine bundle 2.7.0. But in my case the following service definition was not sufficient to get the listener working:

```yaml
services:
    AppBundle\EventListener\EntityListener\ReversalInvoiceListener:
        tags:
            - { name: doctrine.orm.entity_listener, entity: AppBundle\Entity\Accounting\ReversalInvoice, lazy: true }
```

I had to add `@ORM\EntityListeners({"AppBundle\EventListener\EntityListener\ReversalInvoiceListener"})` to the entity. Or is there anything else missing on my definition?

Without the annotation in the entity, the `$metadata->entityListeners` array was empty, so that `ListenersInvoker::getSubscribedSystems` returned 4 instead of 5, which means that the bit for the listener invokation was missing.

So either the documentation is not clear or there is a bug in the code.
