### ISSUE TITLE
Connection overrides dbname with "root"

### ISSUE THREAD

**Issue by afilina** [doctrine/DoctrineBundle#1555]
Fresh installation of latest Symfony on PHP 8.1. Added the orm-pack. Specified `DATABASE_URL`.

The Doctrine connection loaded every single piece of config from the url, but then went and replaced the dbname with `root`. No idea where it's coming from. I have no userland code that contains the word `root` other than my dev mysql credentials. It's a vanilla installation with just twig and orm-pack.

**Comment by afilina** [comment]
My current workaround to this is to specify things separately in the YAML.
```yml
        driver: '%env(resolve:DATABASE_DRIVER)%'
        dbname: '%env(resolve:DATABASE_DBNAME)%'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
        port: '%env(resolve:DATABASE_PORT)%'
        host: '%env(resolve:DATABASE_HOST)%'
```
