### ISSUE TITLE
Configure default schema for all entities

### ISSUE THREAD

**Issue by dmitryuk** [doctrine/DoctrineBundle#1562]
Locally I have two environments: `dev` and `test`.
While `dev` I use SQL dump with a lot of data to easier navigate while development.
While `test` I run tests. Before starting test the script do `schema:drop`, `schema:create` and running Doctrine fixtures.
Finally `test` environment deletes all data, restored in `dev` env.
So I want to configure different database schema (PostgreSQL)  only for `test` env to prevent deleting `dev`'s data.
But I did't find how to set it in symfony config:
```yaml
doctrine:
    dbal:
        connections:
            default:
                driver: '%database_driver%'
                host: '%database_host%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                # I want to set schema here
                #schema: test
```
