### ISSUE TITLE
PDO::ATTR_ enumeration resolution in doctrine yaml

### ISSUE THREAD

**Issue by Dr-Shadow** [doctrine/DoctrineBundle#1563]
Hello is there a way to use the "PDO::ATTR_*" string instead of the constant value inside the options for the DBAL ?

We only succeeded when using the constant value for `PDO::ATTR_STRINGIFY_FETCHES` which is 17 as you can see in our configuration below.

PHP 8.1 switched the default value of `PDO::ATTR_STRINGIFY_FETCHES` from true to false, this is why we needed to make this change on our development version. Relying directly on a constant is probably not what we should be doing.

If needed I would love to document how to use the options in the DBAL configuration as a contribution.

```
doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        driver: pdo_mysql
        host: '_DYNAMIC_DB_'
        port: 3306
        dbname: '_DYNAMIC_NAME_'
        user: '_DYNAMIC_USER_'
        password: '_DYNAMIC_PASSWORD_'
        charset: utf8mb4
        default_table_options:
          charset: utf8mb4
          collate: utf8mb4_unicode_ci
        options:
          17: true
```
