### ISSUE TITLE
Event listener priority is not being respected

### ISSUE THREAD

**Issue by marcospassos** [doctrine/DoctrineBundle#157]
The doctrine event listener priority is not being respected. As you can see, the listeners are being sorted correctly, but the event _doctrine.orm.listeners.resolve_target_entity_ is always executed before the _colibri.listener.add_doctrine_inheritance_discriminator_.

``` php
// Symfony\Bridge\Doctrine\DependencyInjection\CompilerPass\RegisterEventListenersAndSubscribersPass line 79
Array
(
    [colibri.listener.add_doctrine_inheritance_discriminator] => Array
        (
            [event] => Array
                (
                    [0] => loadClassMetadata
                )
            [priority] => 0
        )
    [doctrine.orm.listeners.resolve_target_entity] => Array
        (
            [event] => Array
                (
                    [0] => loadClassMetadata
                )
        )
)
```

There is any workaround for this?

**Comment by caponica** [comment]
I have the same problem... I've tried:

```
# services.yml
services:
    foo_listener:
        class: Caponica\FooBundle\EventListener\FooListener
        tags:
            - { name: doctrine.event_listener, event: postFlush, priority: 100 }
    bar_listener:
        class: Caponica\FooBundle\EventListener\BarListener
        tags:
            - { name: doctrine.event_listener, event: postFlush, priority: 200 }
```

But FooListener still triggers before BarListener. It seems to fire them in the order they are defined rather than respecting the stated priority.
