### ISSUE TITLE
Disable auto mapping in controller resolver results in an exception

### ISSUE THREAD

**Issue by tjveldhuizen** [doctrine/DoctrineBundle#1588]
When I disable the controller resolver as documented at https://symfony.com/doc/current/doctrine.html#automatically-fetching-objects-entityvalueresolver, this results in the following exception. Combined with https://github.com/symfony/symfony/issues/48526, it makes that we can not use Symfony 6.2 at the moment.

> This behavior is enabled by default on all your controllers. You can disable it by setting the doctrine.orm.controller_resolver.auto_mapping config option to false.

```
doctrine:
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        controller_resolver:
            auto_mapping: false
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```

```
In ArrayNode.php line 304:

  Unrecognized option "controller_resolver" under "doctrine.orm.entity_managers.default". Available options are "auto_mapping", "class_metadata_factory_name", "connection", "default_repository_class", "dql", "entity_listener_resolver", "entity_listeners", "filters", "hydrators", "mappings", "metadata_cache_driver", "naming_strategy", "query_cache_driver", "quote_strategy", "repository_factory", "result_cache_driver", "schema_ignore_classes", "second_level_cache".
```

**Comment by dmaicher** [comment]
Can confirm the issue. On one of my projects it also fails. On the other project it works because I specify multiple entity managers there like

```yaml
doctrine:
    orm:
        default_entity_manager: default
        controller_resolver:
            auto_mapping: false
        entity_managers:
            default:
                ...
 ```
