### ISSUE TITLE
EntityListenerPass/AttachEntityListenersListener unaware of 

### ISSUE THREAD

**Issue by BreyndotEchse** [doctrine/DoctrineBundle#1683]
The `Doctrine\ORM\Tools\AttachEntityListenersListener` does not attach any entity listeners targeting interfaces or abstract classes, because it is not aware of the "resolve_target_entites" config option that is used to load ClassMetadata in `Doctrine\ORM\Tools\ResolveTargetEntityListener`.

Dysfunctional config example:
```yaml
# doctrine.yaml
doctrine:
    orm:
        resolve_target_entities:
            FooInterface: Foo
```
```yaml
# services.yaml
services:
    FooListener:
        tags:
            - { name: doctrine.orm.entity_listener, entity: FooInterface }
#                                                              ^- Works only without "Interface" suffix
```
So what I would like to do is:
- Move `ResolveTargetEntityListener::$resolveTargetEntities` to separate service: TargetEntityResolver
- Inject TargetEntityResolver service into ResolveTargetEntityListener and AttachEntityListenersListener
- Forward `ResolveTargetEntityListener::addResolveTargetEntity()` calls to `TargetEntityResolver::addResolveTargetEntity()`
- Add `@deprecated` doc to `ResolveTargetEntityListener::addResolveTargetEntity()`
- Use resolved entities to attach listeners in AttachEntityListenersListener

Any concerns?
