### ISSUE TITLE
doctrine:schema:update --complete not working with multiple entity manager using same connection

### ISSUE THREAD

**Issue by acantepie** [doctrine/DoctrineBundle#1684]
According to [documentation](https://symfony.com/doc/current/doctrine/multiple_entity_managers.html) it's possible to declare multiple manager using same connection like this : 
```
doctrine:
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                        type: attribute
            foo:
                connection: default
                mappings:
                    Foo:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Foo'
                        prefix: 'App\Foo'
                        type: attribute
```

If you doing that,
`bin/console doctrine:schema:update --force --complete --em=default` will sync schema of manager "default" and drop schema of manager "foo"

`bin/console doctrine:schema:update --force --complete --em=foo` will sync schema of manager "foo" and drop schema of manager "default"
