### ISSUE TITLE
setting doctrine.dbal.connections.default.url to null does not make it use explicit config

### ISSUE THREAD

**Issue by mikk150** [doctrine/DoctrineBundle#1699]
Hello.

I am trying to use a project that uses Doctrine.

In it's config there is 

```yaml doctrine.yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
```

I want to override it with config:

``` yaml doctrine-override.yaml
doctrine:
    dbal:
        url: null
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
        host: '%env(resolve:DATABASE_HOST)%'
        port: '%env(resolve:DATABASE_PORT)%'
        dbname: '%env(resolve:DATABASE_NAME)%'
```

But somewhere in the code `null` is casted to string presumably, and now `ConnectionFactory::parseDatabaseUrl()` sees that heyyy... `$params['url']` does exist, so let's try to parse empty string and totally ignores my explicitly set parameters
