### ISSUE TITLE
Multiple entity managers not working with custom repositories

### ISSUE THREAD

**Issue by succinct** [doctrine/DoctrineBundle#171]
I have a use case where we are using two different entity types in two different databases. The configuration is as shown below:

``` yaml
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            accounts:
                driver:   %accounts_database_driver%
                host:     %accounts_database_host%
                port:     %accounts_database_port%
                dbname:   %accounts_database_name%
                user:     %accounts_database_user%
                password: %accounts_database_password%
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager:   default
        entity_managers:
            default:
                connection:       default
            accounts:
                connection:       accounts
                mappings:
                    VoxCoreBundle: ~
```

Two problems are coming up in this environment:
- Generating the entity from the database works, but custom repository classes are NOT being generated, even though they are being specified in annotation:

```
namespace Vox\CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Leaderboard
 *
 * @ORM\Table(name="leaderboard")
 * @ORM\Entity(repositoryClass="Vox\CoreBundle\Entity\Repository\LeaderboardRepository")
 */
class Leaderboard
{
...
```
- After manually generating the custom repository, it is still not being utilized. Custom methods are not called, and instead the following error occurs, indicating (to the best of my knowledge) that the standard EntityRepository is being used:

```
Undefined method 'getTest'. The method name must start with either findBy or findOneBy!
```
