### ISSUE TITLE
Issue with StaticPHPDriver namespace since doctrine/orm 2.3 (breaks since 3.0)

### ISSUE THREAD

**Issue by clementvtrd** [doctrine/DoctrineBundle#1793]
# Context

I'm trying to setup a static php mapping with the following configuration (truncate with unrelated configuration):

```yml
doctrine:
    dbal:
    orm:
        mappings:
            Model:
                type: staticphp
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Entity'
                prefix: 'Infrastructure\Doctrine\Entity'
```

My entity has a `loadMetadata` method and all should be fine.

## Error

However, if I try to run any command that use the default entity manager service, I got the following error:

```
Symfony\Component\ErrorHandler\Error\ClassNotFoundError^ {#4743
  #message: """
    Attempted to load class "StaticPHPDriver" from namespace "Doctrine\ORM\Mapping\Driver".\n
    Did you forget a "use" statement for "Doctrine\Persistence\Mapping\Driver\StaticPHPDriver"?
    """
  #code: 0
  #file: "./var/cache/dev/ContainerJ7M0HEC/getDoctrine_Orm_DefaultEntityManagerService.php"
  #line: 52
```

## Issue

Digging dipper and it appear that the generated class has this line:
```
$b->addDriver(new \Doctrine\ORM\Mapping\Driver\StaticPHPDriver([(\dirname(__DIR__, 4).'/src/Infrastructure/Doctrine/Entity')]), 'Infrastructure\\Doctrine\\Entity');
```

The class `\Doctrine\ORM\Mapping\Driver\StaticPHPDriver` has been removed from [_doctrine/orm_ since v3.0](https://github.com/doctrine/orm/blob/3.1.x/UPGRADE.md#bc-break-remove-staticphpdriver-and-driverchain) and [deprecated since v2.3](https://github.com/doctrine/orm/blob/3.1.x/UPGRADE.md#metadata-drivers).

But the corrected line would be (I guess):
```
$b->addDriver(new \Doctrine\Persistence\Mapping\Driver\StaticPHPDriver([(\dirname(__DIR__, 4).'/src/Infrastructure/Doctrine/Entity')]), 'Infrastructure\\Doctrine\\Entity');
```

I tried to patch the generated class and run, for example, `doctrine:schema:update --dump-sql` and it works.

## Proposal

My suggestion would be to patch the file `config/orm.xml` and replace the value of parameter with key `doctrine.orm.metadata.staticphp.class` with `\Doctrine\Persistence\Mapping\Driver\StaticPHPDriver`.
