### ISSUE TITLE
Overriding xml mappings file ignored

### ISSUE THREAD

**Issue by tito10047** [doctrine/DoctrineBundle#1808]
Hi
I want override xml mappings from Bundle. Its my bundle that I develop and use it in another projects.

In budnle I have definition in ```config/doctrine/Notifier.orm.xml```, there is also other configuration files.
I want override this one file from project so I created same file in same path but in project structure.  But is not working.

Im also tried delete original file (inside bundle) but this new file (in project)  is not registered.

Is this even possible to do? 

here is me config file in project
```yaml
doctrine:
    #...
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            PhpSentinelBundle:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/'
                prefix: 'PhpSentinel\BugCatcher\Entity'
                alias: PhpSentinelBundle
        controller_resolver:
            auto_mapping: false
```

I use newest all packages.

Thanks

**Comment by tito10047** [comment]
It works!!!

Problem was only with bundle name. Bundle name is BugCatcherBundle so configuration need to have same name

here is fixed configuration

```yaml
doctrine:
        #...
        mappings:
            BugCatcherBundle:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/BugCatcherBundle/'
                prefix: 'PhpSentinel\BugCatcher\Entity'
                alias: PhpSentinelBundle
```
