### ISSUE TITLE
Add ability to use services as cache_drivers

### ISSUE THREAD

**Issue by cryptiklemur** [doctrine/DoctrineBundle#182]
It would be awesome if we could define the query_cache_driver as a service.

e.g:

``` yaml
doctrine:
    orm:
        entity_managers:
            default:
                connection: default
                query_cache_driver: @aequasi.memcached
                result_cache_driver: @aequasi.memcached
```
