### ISSUE TITLE
Support SqlServer DSN connection string

### ISSUE THREAD

**Issue by bigfoot90** [doctrine/DoctrineBundle#1848]
## Feature Request
Support SqlServer DSN connection string `dblib://user:password@mssql:1433/OMSV?charset=utf8mb4`

#### First try
doctrine.yaml:
```yaml
doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '11.5.2-mariadb'
            mssql:
                url: '%env(resolve:MS_SQL_URL)%'
        default_connection: default
```
Error:
```
The given driver "dblib" is unknown, Doctrine currently supports only the following drivers: pdo_mysql, pdo_sqlite, pdo_pgsql, pdo_oci, oci8, ibm_db2, pdo_sqlsrv, mysqli, pgsql, sqlsrv, sqlite3
```

#### Second try
.env:
```
MS_SQL_URL=pdo_sqlsrv://user:password@mssql:1433/OMSV?charset=utf8mb4
```
Error:
```
An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory
```
I think it is trying to connect using the wrong driver

#### Third try
doctrine.yaml: (explicit driver config)
```yaml
doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '11.5.2-mariadb'
            mssql:
                driver: pdo_sqlsrv
                url: '%env(resolve:MS_SQL_URL)%'
        default_connection: default
```
Error:
<img width="882" alt="image" src="https://github.com/user-attachments/assets/da4475d4-e809-4d3f-bd17-ccd29fb9513a" />
Only the charset was detected correcly

#### Fourth try
.env:
```
MS_SQL_URL=sqlsrv://user:password@mssql:1433/OMSV?charset=utf8mb4
```
doctrine.yaml:
```yaml
doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '11.5.2-mariadb'
            mssql:
                driver: pdo_sqlsrv
                url: '%env(resolve:MS_SQL_URL)%'
        default_connection: default
```
For this I had to install more php modules, and other [microsoft's proprierary libraries](https://learn.microsoft.com/it-it/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16&tabs=alpine18-install%2Calpine17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline) and most important I had to migrade from dblib to sqlsrv.

### Why

I would like to configure the connection using just one single connection string containing all the parameters (DSN) as I do for mysql.

Also I didn't found any documentation on [symfony docs](https://symfony.com/doc/current/doctrine.html) or over the internet

**Comment by bigfoot90** [comment]
Finally I ended by writing my own Driver class to not change my environment and do not rewrite my legacy code.
.env:
```
MS_SQL_URL=//user:password@mssql:1433/OMSV?charset=UTF-8
```
doctrine.yaml:
```yaml
doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '11.5.2-mariadb'
            mssql:
                driver_class: Infrastructure\Persistence\Doctrine\Driver\DbLibDriver
                url: '%env(resolve:MS_SQL_URL)%'
        default_connection: default
```
If you wish i can create a gist of this class or maybe better submit a PR to doctrine/dbal repository.
