### ISSUE TITLE
how to use another MySQL environment variable than the base one to save its data?

### ISSUE THREAD

**Issue by aragon5956** [doctrine/DoctrineBundle#1858]
[eng]Hello,
I would like to know , how to use another MySQL environment variable than the base one to save its data?
Could you help me ?

[Fr]Bonjour,
Je voudrais savoir, comment utiliser une autre base de données de MySQL pour sauvegarder les données, pourriez vous m'aider ?
Cordialement

**Comment by nicolas-grekas** [comment]
have a look at config/packages/doctrine.yaml file, that's where the current env var is linked to Symfony
you can change this at will

**Comment by aragon5956** [comment]
no I want to add another environment variable, for the mmement , i've this : 
```
doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '8.0.37'
        charset: utf8mb4
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
```

Can I add another?
