### ISSUE TITLE
Mapping exception on multiple entity managers

### ISSUE THREAD

**Issue by marfillaster** [doctrine/DoctrineBundle#188]
[Doctrine\Common\Persistence\Mapping\MappingException]
  The class 'UserBundle\Entity\User' was not found in the chain configu
  red namespaces SomeBundle\Entity

The exception above happens when a bundle's entities are assigned to non-default entity manager. The only remedy as of the moment is to re-declare the Entity mapping on default manager.

Example working config

```
orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager:   default
        entity_managers:
            ebeis:
                connection: alternate
                mappings:
                    UserBundle: ~

            default:
                connection: default
                mappings:
                    DefaultBundle: ~
                    UserBundle: ~ # removing this will throw the MappingException
```
