### ISSUE TITLE
What is the idiomatic way to register your own Driver?

### ISSUE THREAD

**Issue by theofidry** [doctrine/DoctrineBundle#1882]
The PR https://github.com/doctrine/DoctrineBundle/pull/1832 which was released in 2.13.1 introduced a big change in the way drivers are registered. Indeed previously it was possible to register your own driver by setting the driver class parameter, e.g. `doctrine.orm.metadata.xml.class`.

Is there an alternative way that I am missing to achieve the equivalent now? Because currently the only way I can see is extending the extension to override [the `getMetadataDriverClass()` method](https://github.com/doctrine/DoctrineBundle/blob/be90446a11efd00a1f48ed1857b5fadbce8f5481/src/DependencyInjection/DoctrineExtension.php#L1138) and then register your own bundle instead of the Doctrine one, which sounds a bit extreme and a lot of boilerplate.

When I asked in the Symfony slack I was asked the use case, mine is relatively simple: we register a custom XML driver that can interpret some extra arbitrary options from the XML file.

**Comment by theofidry** [comment]
This is prompted by [this initiative](https://github.com/doctrine/DoctrineBundle/issues/630).

The question is if it is really desirable. The initiative is quite old and from some comments it is because this was used a bit too much for a lot of cases where it would be easy and more conventional to decorate services (see https://github.com/symfony/symfony/issues/21735#issuecomment-338972790).

I don't have a strong opinion on the subject. I'm more interested in having an extension point to register a custom driver, which is something that works just fine in Doctrine ORM itself (see [the docs](https://www.doctrine-project.org/projects/doctrine-orm/en/3.3/reference/metadata-drivers.html)).

If you feel strongly about removing the parameters, maybe a different approach would be to allow an arbitrary key to allow a custom driver:

```yaml

doctrine:
    orm:
        mappings:
            domain:
                type: custom_xml
                dir: "%kernel.project_dir%/resources/config/doctrine"
                prefix: App\Entity
                is_bundle: false
```
