### ISSUE TITLE
custom type is not defined as well

### ISSUE THREAD

**Issue by AlmogBaku** [doctrine/DoctrineBundle#200]
After defining my custom types in the config.yml, it works as well when I use `doctrine:schema:create` but its start to throw errors with `doctrine:schema:drop` or `doctrine:schema:update`

Config:

``` yaml
doctrine:
    dbal:
        ...
        types:
            geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            linestring: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType
```

The console error:

``` console
$ app/console doctrine:schema:drop --dump-sql

  [Doctrine\DBAL\DBALException]                                                                     
  Unknown database type point requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.
```

Also, if I add

``` yaml
mapping_types:
            point: point
```

Its throw me another error:

``` console
Unknown column type "Point" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType().
```

So its seems that the registration of the type is not doing as well.
## 
- I used https://github.com/djlambert/doctrine2-spatial to define the spatial point.
