### ISSUE TITLE
ORM Mapping - map from multiple directories

### ISSUE THREAD

**Issue by pleerock** [doctrine/DoctrineBundle#209]
We need to add extra support to map entities from multiple directories, like this:

``` yaml

doctrine:
   orm:
      mappings:
         default:
             AcmeDemoBundle:
                 type: "annotation"
                 dir: ["Entity", "DefaultEntityImplementations"]
         test:
             AcmeDemoBundle:
                 type: "annotation"
                 dir: ["Entity", "TestEntityImplementations", "SomeOtherDirWIthEntities"]
```

because sometimes entities can be in different directories, but there is no support of this. This is a duplicate of the issue in the [Symfony issues](https://github.com/symfony/symfony/issues/8959)

**Comment by garex** [comment]
**Workaround**

1. In extension define some param with path to your bundle
2. In mappings use is_bundle: false and path with param prepended

**Comment by TomasVotruba** [comment]
Any updates on this?

**Comment by TavoNiievez** [comment]
I have a DDD style directory structure, and for example, i have one entity in the path `App\Person\User\Domain\Model\User` and another in the path `App\Person\Employee\Domain\Model\Employee`. So I decided to create a common directory (with common prefix as well):
```php
    $configurator->extension('doctrine', [
        'orm' => [
            'mappings' => [
                'Person' => [
                    'is_bundle' => false,
                    'type' => 'xml',
                    'dir' => '%kernel.project_dir%/config/mapping/Person',
                    'prefix' => 'App\Person',
                    'alias' => 'Person'
                ],
				//...
            ]
        ]
    ]);
```
And just specified the folders they are located in the name of the `.orm.xml` file.
```
User.Domain.Model.User.orm.xml
Employee.Domain.Model.Employee.orm.xml
```

If you don't choose a prefix, you should be able to navigate the entire `src` folder on the filename.

It's a hacky way of doing it, but it works quite well.

**Comment by Richard87** [comment]
#Fixed!

Hi! I just tried to do the same:

```yaml
doctrine:
  orm:
    entity_managers:
      default:
        mappings:
          App:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Entity'
            prefix: 'App\Entity'
            alias: App
          FancyPants:
            type: attribute
            dir: '%kernel.project_dir%/src/Domain/FancyPants/Entity'
            prefix: 'FancyPants\Entity'
            alias: FancyPants
            is_bundle: false
```

But the Entities in `'%kernel.project_dir%/src/Domain/FancyPants/Entity'` is not found when running `bin/console doctrine:mapping:info`.... Is any other config required? 

For completness, I also have ApiPlatform operations on the same entities, and they work nicely:
```yaml
api_platform:
  mapping:
    paths:
    - '%kernel.project_dir%/src/Entity'
    - '%kernel.project_dir%/src/Domain/FancyPants/Entity'
```

[EDIT] I also flushed all redis cache, and deleted var/cache just in case... 

[EDIT2] Prefix must be the whole namespace, so changing it to `prefix: 'App\Domain\FancyPants\Entity'` solved my issue :)  Leaving it here in case other stumbles upon it!

**Comment by dmaicher** [comment]
I'm also doing this on one of my projects like

```yaml
doctrine:
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Alias1:
                        dir: '%kernel.project_dir%/src/Namespace1/Entity
                        prefix: App\Namespace1\Entity
                    Alias2:
                        dir: '%kernel.project_dir%/src/Namespace2/Entity
                        prefix: App\Namespace2\Entity
```

So I don't think there is anything to be done here?
