### ISSUE TITLE
Mapping entities outside a Bundle using YAML

### ISSUE THREAD

**Issue by theUniC** [doctrine/DoctrineBundle#216]
Hi all,

Would like to know what's the best way to map entities outside bundles using YAML. I've a tree structre like the one below

```
| src
| -- Vendor
| ------ Bundle
| --------- Context1Bundle
| ------------- Resources
| ------------------ config
| --------------------- doctrine
| --------------------------- Subcontext1
| -------------------------------- EntityInSubcontext1.orm.yml
| --------------------------- Subcontext2
| -------------------------------- EntityInSubcontext2.orm.yml
| ------ Context1
| --------- Domain
| ------------- Model
| ----------------- Subcontext1
| ---------------------- EntityInSubcontext1.php
| ----------------- SubContext2
| ---------------------- EntityInSubcontext2.php
```

My doctrine config is like this one

``` yml
doctrine:
    dbal:
        driver:   pdo_sqlite
        charset:  UTF8
        path:     "%database_path%"

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: false
                mappings:
                    subcontext1_mapping:
                        type: yml
                        dir: "%kernel.root_dir%/../src/Vendor/Bundle/Context1Bundle/Resources/config/doctrine/Subcontext1"
                        prefix: Vendor\Context1\Domain\Model\Subcontext1
                        is_bundle: false
                        alias: Subcontext1Mapping

                    subcontext2_mapping:
                        type: yml
                        dir: "%kernel.root_dir%/../src/Vendor/Bundle/Context1Bundle/Resources/config/doctrine/Subcontext2"
                        prefix: Vendor\Context1\Domain\Model\Subcontext2
                        is_bundle: false
                        alias: Subcontext2Mapping
```

And the mapping file "EntityInSubcontext1.orm.yml" looks like this

``` yml
Vendor\Context1\Domain\Model\Subcontext1\EntityInContext1:
    type: entity
    table: entity_in_context1

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 255
            nullable: true
            unique: true
```

When I try to generate a doctrine crud from this entity, for example

``` shell
> php app/console generate:doctrine:crud --with-write --entity=VendorContext1Bundle:EntityInSubcontext1
```

Leads to the error message **"Unknown Entity namespace alias 'VendorContext1Bundle'**.

Am I missing something?

Thanks!
