### ISSUE TITLE
Using the doctrinebundle with entities without namespaces

### ISSUE THREAD

**Issue by WouterSioen** [doctrine/DoctrineBundle#234]
Hi,

I'm trying to implement the DoctrineBundle in a PHP project that isn't using namespaces yet. Is it possible to persist Entities without namespaces to doctrine with this bundle. The Entities get loaded with the autoloader of this project, so no includes are needed.

I tried this but it doesn't seem to work:

```
orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    auto_mapping: true
    mappings:
        BlogPost:
            type: annotation
            dir: %kernel.root_dir%/../backend/modules/blog/entity
            prefix: \
```

and in the code

```
$em = $this->get('doctrine')->getManager();
$blogpost = new BlogPost();

...

$em->persist($blogpost);
```

I get this error:

```
The class 'BlogPost' was not found in the chain configured namespaces \
```
