### ISSUE TITLE
How do I configure the Xml-Metadata-Driver?

### ISSUE THREAD

**Issue by fadoe** [doctrine/DoctrineBundle#237]
How can I configure Symfony to use in one Bundle or Library the Doctrine\ORM\Mapping\Driver\XmlDriver? I have a library used in ZendFramework and the Doctrine\ORM\Mapping\Driver\XmlDriver, but I didn't found a way to configure Symfony to use only this library with the XmlDriver.

Example configuration:

```
// services.xml
    <parameters>
        <parameter key="doctrine.orm.metadata.defaultxml.class">Doctrine\ORM\Mapping\Driver\XmlDriver</parameter>
    </parameters>

// config.yml
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                mappings:
                    my_library:
                        type: defaultxml
                        prefix: My\Library\Entity
                        dir: %kernel.root_dir%/../src/My/Library/config/doctrine
                        is_bundle: false
```

Result:

```
InvalidArgumentException: Can only configure "xml", "yml", "annotation", "php" or "staticphp" through the DoctrineBundle. Use your own bundle to configure other metadata drivers. You can register them by adding a new driver to the "doctrine.orm.default.metadata_driver" service definition.
```

**Comment by philgagnon12** [comment]
You would have to add the driver through a *CompilerPass*.

Here's a simple example, I'm adding the traditional *Doctrine\ORM\Mapping\Driver\YamlDriver* driver to the *DriverChain*


**DependencyInjection/Compiler/YamlDriverCompilerPass.php**
````
<?php

namespace Acme\AcmeBundle\DependencyInjection\Compiler;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Reference;

class YamlDriverCompilerPass implements CompilerPassInterface{
   
    public function process(ContainerBuilder $container){

        $driverChainDef = $container->findDefinition('doctrine.orm.default_metadata_driver');

        $driverChainDef->addMethodCall('addDriver', array(
                new Reference('acme.yaml_driver'),
                'Acme\\AcmeBundle\\Entity' 
            )
        );
    }
    
}

````


**Resources/config/services.yml**
````
services:
    acme.yaml_driver:
        class: Doctrine\ORM\Mapping\Driver\YamlDriver
        arguments: 
            - 
                - "%kernel.root_dir%/../vendor/acme/ORM/Doctrine/Mapping"
            - ".dcm.yml"
````


**AcmeBundle.php**
````
<?php

namespace Acme\AcmeBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;
use Symfony\Component\DependencyInjection\ContainerBuilder;

use Acme\AcmeBundle\DependencyInjection\Compiler\YamlDriverCompilerPass;

class AcmeBundle extends Bundle
{

    public function build(ContainerBuilder $container)
    {
        parent::build($container);

        $container->addCompilerPass(new YamlDriverCompilerPass());
    }

}
````
