### ISSUE TITLE
Configure defaults for all entity_manages

### ISSUE THREAD

**Issue by jaymecd** [doctrine/DoctrineBundle#289]
Would be good to configure defaults in intelligent way for all entity_managers, where last one could overwrite with own value or reset to system default.

For example, this snippet sets cache drivers only to the `default` em:

```
doctrine:
  orm:
    metadata_cache_driver: apc
    result_cache_driver: memcached
    query_cache_driver: memcached
  entity_managers:
    default:
      ...
    custom1:
      result_cache_driver: ~ # reset
      ...
    custom2:
      metadata_cache_driver: array
      query_cache_driver: redis
      ...
```

Expected:
- `default` has _apc/memcached/memcached_
- `custom1` has _apc/array/memcached_
- `custom2` has _array/memcached/redis_ 

Current:
- `default` has _apc/memcached/memcached_
- `custom1` and `custom2` has system default - _array_
