### ISSUE TITLE
Can't set Cache Namespace in Config

### ISSUE THREAD

**Issue by heikokrebs** [doctrine/DoctrineBundle#291]
Per default the Cache Namespace is generated automatically, part of the Hash, used for the name, is the environment. 
If i want to set a custom Namespace i can do this in the config. 

Example:  

```
doctrine:
  orm:
    result_cache_driver:
      type: memcached
      host: ...
      port: ...
      namespace: MyCustomNamespace
```

The problem is, this namespace is never set, the namespace is just an empty string.
