### ISSUE TITLE
Entity Listener : Inject a service containing entity manager

### ISSUE THREAD

**Issue by mehdi-ghezal** [doctrine/DoctrineBundle#300]
Hello,

With the following services configuration we get this exception :

```
ORMException: It's a requirement to specify a Metadata Driver and pass it to Doctrine\ORM\Configuration::setMetadataDriverImpl().
```

_Services configuration_

``` yml
services:
    acme.invoice.listener:
        class: %acme.invoice.listener.class%
        arguments:
            - "@acme.invoice.manager"
        tags:
            - { name: doctrine.orm.entity_listener }

    acme.invoice.manager:
        class: %acme.invoice.manager.class%
        arguments:
            - "@doctrine.orm.entity_manager"
```

I think that DoctrineBundle get all services related to my listener before Doctrine Initialization then the Entity Manager is not yet fully configure. I try to use lazy service but I have the same issue.

Hope this report can help you to make DoctrineBundle more awesome ;)
