### ISSUE TITLE
Non-bundle mapping issue (Prefix ending with '\' is not respected)

### ISSUE THREAD

**Issue by pawelbaranski** [doctrine/DoctrineBundle#304]
Hello

Mapping of non-bundle resources does not seem to work as expected in one particular case. I was stuggling with the issue, until I surprisingly overcame it by moving my model class to separate directory. I am not happy with it, since I had to change my structure to make it work with Doctrine.

Here is the case:

orignal situation looked like this. I had a lone Token class that was outside a bundle with  its mapping settings and config.yml configured so that Doctrine can find mapping for the class

 my config.yml

```
doctrine:
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    devhelp_token:
                        is_bundle: false
                        type: yml
                        prefix: Devhelp\Token\
                        dir: %kernel.root_dir%/../src/Devhelp/Token/Bridge/Doctrine/Resources/mapping
```

relevant parts of dir structure

```
src/
└── Devhelp
    ├── Token
    │   ├── Bridge
    │   │   └── Doctrine
    │   │       └── Resources
    │   │           └── mapping
    │   │               └── Token.orm.yml
    │   └── Token.php
    └── TokenDemoBundle
        ├── Entity
        │   ├── ConfirmUpdateToken.php
```

Token.orm.yml

```
Devhelp\Token\Token:
    type: mappedSuperclass
    fields:
        type:
        hash:
        usages:
            type: integer
            nullable: true
        expiresAt:
            column: expires_at
            type: datetime
            nullable: true
```

Token.php

```
<?php

namespace Devhelp\Token;


class Token
{

    /**
     * @var string
     */
    protected $type;

    /**
     * @var string
     */
    protected $hash;

    /**
     * @var int
     */
    protected $usages;

    /**
     * @var \DateTime
     */
    protected $expiresAt;
}
```

ConfirmUpdateToken.php

```
<?php

namespace Devhelp\TokenDemoBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Devhelp\Token\Token;

/**
 * @ORM\Entity
 * @ORM\Table(name="confirm_update_tokens")
 */
class ConfirmUpdateToken extends Token
{
    /**
     * @var integer
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var array
     * @ORM\Column(type="array")
     */
    private $data;
}
```

Once I run doctrine:schema:validate I got

```
PHP Fatal error:  Cannot redeclare class Devhelp\Token\Token in /home/devhelp/devhelp-token-bundle-sandbox/src/Devhelp/Token/Token.php on line 7
```

Now I know the reason. It was because prefix setting in config.yml ended with '\'. I had to  place '\' because prefix 'Devhelp\Token' is ambiguous since there is 'Devhelp\TokenDemoBundle' (without '\' prefix matches this namespace as well). Without '\' I was getting an error that mapping for ConfirmUpdateToken does not exists because doctrine was searching in "%kernel.root_dir%/../src/Devhelp/Token/Bridge/Doctrine/Resources/mapping" which did not contain the mapping of course. I had to move Devhelp/Token/Token.php to Devhelp/Token/Model/Token.php and change 'prefix' to 'Devhelp\Token\Model' to make it work together.
