### ISSUE TITLE
Relationships with Abstract Classes and Interfaces (Multiple)

### ISSUE THREAD

**Issue by rkmax** [doctrine/DoctrineBundle#328]
Background do not know the problems they may have. but I have the following requirement:

Many of my entities are related to one-to-many with the same entity
![problem](https://cloud.githubusercontent.com/assets/395707/4150993/3bab3ff0-3442-11e4-92ad-1e671bae32be.jpg)

As each entity has exactly the same property and the same methods, I've modeled so
![solution](https://cloud.githubusercontent.com/assets/395707/4151002/439a9f76-3442-11e4-86ba-a649139df059.jpg)

I extracted an interface of the abstract class and use the relationship many-to-one in the File entity

In theory it works fine, the problem is how to tell doctrine to use a single property, naively thought I could use the **resolve_target_entities**, but logically only allows a scalar value and not an array

i need this on the config.yml

``` yaml
orm:
    # ...
    resolve_target_entities:
       Vendor\Interface: [Vendor\Entity\Person, Vendor\Entity\Company, ... ]
```

or better **A solution that works with Doctrine as such :+1:**

There is a question on [Stackoverflow](http://stackoverflow.com/questions/25649773/relationships-with-abstract-classes-and-interfaces-multiple)

**Comment by jmunozco** [comment]
Hi @rkmax, did you find how to do it? I'm facing the same problem... Thanks!

**Comment by anis-marrouchi** [comment]
Have you tried using a variable parameter like so:
```yml
parameters:
    your_default_concrete_class: "Class\One"
   all_my_concrete_classes: [Class\Two,Class\Three,Class\Four...]
orm:
    # ...
    resolve_target_entities:
       Vendor\Interface: %your_default_concrete_class%
```
then you handle the logic in your controller | formType,| entityRepository.
Can we use interfaces for the class attribute in the formType?
I'm just curious if this would be possible in RDBMS paradigm.
