### ISSUE TITLE
cache driver configuration BC BREAK

### ISSUE THREAD

**Issue by mvrhov** [doctrine/DoctrineBundle#345]
In earlier 1.3 and 1.2 the cache configuration was possible like.

``` yaml
doctrine:
    orm:
        entity_managers:
            default:
                metadata_cache_driver:  redis
                query_cache_driver:     redis
```

Currently the cache MUST be configured like:

``` yaml
doctrine:
    orm:
        entity_managers:
            default:
                metadata_cache_driver:
                    type: redis
                    host: localhost
                    port: 6379
                query_cache_driver:
                    type: redis
                    host: localhost
                    port: 6379
```

It looks like the the defaults are not used anymore which is quite a shame.
