### ISSUE TITLE
proxies are still auto-generated with auto_generate_proxy_classes set to false

### ISSUE THREAD

**Issue by nimasdj** [doctrine/DoctrineBundle#369]
I still get proxies auto-generated with auto_generate_proxy_classes set to false.

``` yaml
    orm:
        auto_generate_proxy_classes: false
        proxy_namespace: Proxies
        proxy_dir: doctrine/Proxies
        default_entity_manager: default # The first defined is used if not set
        entity_managers:
             default:
                    connection: default
                    auto_mapping: false
                    mappings: # Required
```
