### ISSUE TITLE
The service "cache_warmer" has a dependency on a non-existent service "doctrine". 

### ISSUE THREAD

**Issue by makasim** [doctrine/DoctrineBundle#395]
If I configure the orm part but leave the dbal part empty the exception `The service "cache_warmer" has a dependency on a non-existent service "doctrine". ` will be thrown. The service `doctrine` is defined in `dbal.xml` and since the file is not load we do not have this service. But at the same time we have some mappings and cache warmer tries to do its job and fails. It was initially reported here https://github.com/Payum/PayumBundle/issues/241 because of the [prepend config](https://github.com/Payum/PayumBundle/blob/master/DependencyInjection/PayumExtension.php#L86)

An example:

```
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    payum:
                        is_bundle: false
                        type: xml
                        dir: %kernel.root_dir%/../vendor/payum/core/Payum/Core/Bridge/Doctrine/Resources/mapping

                        prefix: Payum\Core\Model
```

and run command 

```
app/console cache:warmup
```

It is better to move doctrine service in another place. Which one? Workaround for now:

* If you dont need the DoctrineBundle do not register it in AppKernel.
* If you need it then configure the connection to a database.
