### ISSUE TITLE
Custom platform is not taken into account

### ISSUE THREAD

**Issue by cariboo** [doctrine/DoctrineBundle#4]
When defining a custom platform in the configuration of Symfony 2 like below (config.yml) :

```
services:
    my_platform:
        class: Doctrine\DBAL\Platforms\MyPlatform

doctrine:
    dbal:
        options:
            driver: %driver%
            platform: @my_platform
```

the custom platform MyPlatform is not taken into account and the driver default one is used instead.

**Comment by amcastror** [comment]
Hi, I'm trying to do this on Symfony 3.2 and I am having the same issue.. the platform isn't taken into account:

```
services:
    wc_platform:
        class: AppBundle\Doctrine\CustomPlatform

doctrine:
    dbal:
        options:
            platform_service: wc_platform
```

Is this still the correct way?

Thanks.
