### ISSUE TITLE
serverVersion isn't found when MasterSlaveConnection is used

### ISSUE THREAD

**Issue by tiger-seo** [doctrine/DoctrineBundle#410]
```yaml
# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        server_version: 5.6
        slaves:
            slave1:
                host:     %database_slave1%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
```
unfortunately, this configuration will not prevent `auto-detection of platform` (details in #351 )
and this happens because serverVersion is being moved to master config in `_params` of the `MasterSlaveConnection`, but `\Doctrine\DBAL\Connection::getDatabasePlatformVersion` expects `serverVersion` in root of `_params`

good news is, i already fixed this for myself and going to provide PR
