### ISSUE TITLE
Cross-bundle/entity-manager inheritance not working

### ISSUE THREAD

**Issue by Uncaught-Exception** [doctrine/DoctrineBundle#422]
Hello, I have two entities with some similar fields in different bundles of my application. Both bundles use a different database/connection/manager.

I created a mapped superclass 
```yml
App\Bundle1\Entity\BaseDomain:
  type: mappedSuperclass
  fields:
    domain:
      type: string
      length: 255
      nullable: false
      column: domain
```
and the two extending entities
```yml
App\Bundle1\Entity\Domain1:
  type: entity
  extends: BaseDomain
  fields:
    id:
      id: true
      type: integer
      column: id
      generator:
        strategy: IDENTITY
```
```yml
App\Bundle2\Entity\Domain2:
  type: entity
  extends: App\Bundle1\Entity\BaseDomain
  fields:
    id:
      id: true
      type: integer
      column: id
      generator:
        strategy: IDENTITY
```

The relevant doctrine configuration is as such:
```yml
doctrine:
    orm:
      entity_managers:
        one:
          connection: one
          mappings:
            Bundle1:
              mapping: true
              type: yml
              dir: Resources/config/doctrine
              prefix: App\Bundle1\Entity
        two:
          connection: two
          mappings:
            AppBundle2:
              mapping: true
              type: yml
              dir: Resources/config/doctrine
              prefix: App\Bundle2\Entity
```

The Domain1 is working fine. doctrine:migrations:diff works as expected and the entities load completely.
Domain2 however does not work. doctrine:migrations:diff throws this exception:
```
[Doctrine\DBAL\Schema\SchemaException]                     
  There is no column with name 'domain' on table 'domains'.
```
which is weird in itself because I thought the diff should create an alter-statement for missing columns. (The column is there though, the table is complete, I only use migrations:diff to check if the configuration is complete.)
And if I load the Domain2 entities, I get them without errors, but the "domain"-field is not being filled with data (remains NULL in PHP).

I also tried putting a slash in front of the namespace in the second "extends" without success.

If I copy the BaseDomain.orm.yml and the BaseDomain.php over to the Bundle2 and adjust the namespaces, both entities work perfectly.

So it seems the cross-bundle or cross-entity-manager inheritance is broken. Or this was not implemented, yet.

If you need more information, please advice!
