### ISSUE TITLE
Doctrine mapping import ignores filter when checking tables for primary keys

### ISSUE THREAD

**Issue by markusgillmeister** [doctrine/DoctrineBundle#441]
I ran into an issue when importing a mapping from a single table. The database has some tables without primary keys which are not important for my import. So I use the filter parameter to get only the single table. But doctrine does a complete database check and throws a MappingException when scanning the table without the primary key.

> console doctrine:mapping:import --em=customer **--filter="tbl_users"** AcmeHelloBundle xml

>  [Doctrine\ORM\Mapping\MappingException]
>  **Table tbl_abc has no primary key**. Doctrine does not support reverse engineering from tables that don't have a primary key.

I think it would be better if the mapping import only does the check on the mentioned table in the filter parameter und do the import.

**Comment by mat-m** [comment]
I confirm the issue

**Comment by axeff** [comment]
+1

**Comment by jderusse** [comment]
:+1:

**Comment by axeff** [comment]
As workaround I created a new database with just the table I wanted to import.

**Comment by remmel** [comment]
agree

**Comment by yezongyang** [comment]
+1

**Comment by yangconghou** [comment]
agree verymuch!!

**Comment by mikeSimonson** [comment]
If I remember well the table filter works if you use it on the connection directly.
Like this

```yml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            customer:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                schema_filter: tbl_users
```

And I use the customer connection to create the customer entity manager

```yml
orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                            .....
            customer:
                connection: customer #Here comes the already filtered connection
```

Now you can just pass your custom entity manager (customer) with your filtered connection (customer) to the import command.
