### ISSUE TITLE
Using password for Redis cache

### ISSUE THREAD

**Issue by thedamnedrhino** [doctrine/DoctrineBundle#453]
Currently there is no way to easily set a password for a cache driver as addressed in [this Question](http://stackoverflow.com/questions/31980070/doctrine-connect-to-redis-with-password) and because of [this piece of Code](https://github.com/doctrine/DoctrineCacheBundle/blob/master/DependencyInjection/SymfonyBridgeAdapter.php#L120), the same goes for DoctrineCacheBundle as stated in the documentation, but it looks like it is [actually supported](https://github.com/doctrine/DoctrineCacheBundle/blob/master/DependencyInjection/Definition/RedisDefinition.php#L58). Is there a reason behind this, or am I missing something?

**Comment by rogeriolino** [comment]
I've the same issue.

For while in the master, the code use password if setted:

https://github.com/doctrine/DoctrineCacheBundle/blob/master/DependencyInjection/SymfonyBridgeAdapter.php#L126

But if you add password on your config file throws this exception:

    Unrecognized option "password" under "doctrine.orm.entity_managers.default.metadata_cache_driver"

**Comment by rogeriolino** [comment]
Solved using DoctrineCacheBundle:

```yaml
doctrine_cache:
    providers:
        my_provider:
            redis:
                host: hostname
                port: 6379
                password: foobared
```

then

```yaml
doctrine:
    orm:
        metadata_cache_driver:
            type: service
            id: doctrine_cache.providers.my_provider
```
