### ISSUE TITLE
Hardcoded defaults from Configuration override values from configured URL

### ISSUE THREAD

**Issue by dzuelke** [doctrine/DoctrineBundle#459]
The following does not work:

```
doctrine:
    dbal:
        url: "postgres:/
/snoopy:woodstock@redbaron.peanuts.com:5432/darkandstormynight"
        charset:  UTF8
```

because this gets generated:

```php
    protected function getDoctrine_Dbal_DefaultConnectionService()
    {
        return $this->services['doctrine.dbal.default_connection'] = $this->get(
'doctrine.dbal.connection_factory')->createConnection(array('url' => 'postgres:/
/snoopy:woodstock@redbaron.peanuts.com:5432/darkandstormynight', 'charset' => 'UTF8', 'host' => 'localhost', 'port' =>
 NULL, 'user' => 'root', 'password' => NULL, 'driver' => 'pdo_mysql', 'driverOpt
ions' => array()), new \Doctrine\DBAL\Configuration(), new \Symfony\Bridge\Doctr
ine\ContainerAwareEventManager($this), array());
    }
```

The reason is in `DoctrineBundle/DependencyInjection/Configuration.php`:

```php
    private function getDbalConnectionsNode()
    {
        // ...
        $this->configureDbalDriverNode($connectionNode);
        $connectionNode
            ->fixXmlConfig('option')
            ->fixXmlConfig('mapping_type')
            ->fixXmlConfig('slave')
            ->fixXmlConfig('shard')
            ->children()
                ->scalarNode('driver')->defaultValue('pdo_mysql')->end()
        // ...
        ;
    }
    // ...
    private function configureDbalDriverNode(ArrayNodeDefinition $node)
    {
        $node
            ->children()
                ->scalarNode('url')->info('A URL with connection information; any parameter value parsed from this string will override explicitly set parameters')->end()
                ->scalarNode('dbname')->end()
                ->scalarNode('host')->defaultValue('localhost')->end()
                ->scalarNode('port')->defaultNull()->end()
                ->scalarNode('user')->defaultValue('root')->end()
        // ...
        ;
    }
```

The workaround currently has to be the following:

```
doctrine:
    dbal:
        driver: null
        host: null
        user: null
        url: "postgres:/
/snoopy:woodstock@redbaron.peanuts.com:5432/darkandstormynight"
        charset:  UTF8
```

That's clearly not convenient.

I am not familiar enough with Symfony's Configuration component; is it possible to define a default value depending on whether or not another node exists? Surely @fabpot or @stof would know? :)

The alternative would be for the URL information to just not be merged with any other parameters, but the intention is and was (DBAL alone behaves like this too) that explicit parameters can override information from the URL.
