### ISSUE TITLE
Connection Configuration via URL Causes Drop/Create Commands to Fail

### ISSUE THREAD

**Issue by chrisguitarguy** [doctrine/DoctrineBundle#464]
In both the Drop and Create database commands, the database name is extracted from the connection parameters then removed before `DriverManager::getConnection` is called. If you configure with a URL however, the URL remains the connection is still attempted with the database name in place which fails if the database doesn't exist.

Example configuration:

```yaml
doctrine:
  dbal:
    url: mysql://root@localhost/dbname
```

Should just need to `unset($params['url'])` in each command.
