### ISSUE TITLE
Embedded objects don't include their relationships

### ISSUE THREAD

**Issue by danwkennedy** [doctrine/DoctrineBundle#471]
In my data model, I've got a Cost object that keeps track of a the cost value and the currency of an item. The mapping is as follows:

Item.orm.yml:
```
Item:
   type: entity
   embedded:
      cost:
         class: My\Class\Cost
```

Cost.orm.yml:
```
Cost:
   type: embeddable
   oneToOne:
      currency:
         targetEntity: My\Class\Currency
      joinColumn:
        name: currency_id
        referencedColumnName: id
    fields:
        value: { type: string }
```

I would expect the Item table to have `cost_value` and `cost_currency_id` columns however only `cost_value` gets carried over.
