### ISSUE TITLE
Multiple entity listener resolver .?

### ISSUE THREAD

**Issue by ahmedwafdi** [doctrine/DoctrineBundle#480]
Hello i created two entity listener for two differents Entities RendezVous (entity) and Instruction (entity) 
so i created "RendezVousListener" and "InstructionListener"  each one in differents Bundles .
in my config.yml i declared the listeners as services .
config.yml :

 services:
    #  service notification pour les instructions (consigne) 
    instruction_Instruction.doctrine.entity_listener_resolver:
        class: Instruction\InstructionBundle\Doctrine\EntityListenerResolver
        arguments: [ "@service_container" ]

```
instruction_Instruction.entity_listener.instruction:
    class: Instruction\InstructionBundle\Listener\InstructionListener
    arguments: [ '@service_container' ]
    tags:
        -  { name: doctrine.entity_listener }
```
# #  service des SMS pour les Rdv

```
rendezvous_RendezVous.doctrine.rdv_entity_listener_resolver:
    class: RendezVous\RendezVousBundle\Doctrine\RdvEntityListenerResolver
    arguments: [ "@service_container" ]

rendezvous_RendezVous.entity_listener.rendezvous:
    class: RendezVous\RendezVousBundle\Listener\RendezVousListener
    arguments: [ '@service_container' ]
    tags:
        -  { name: doctrine.entity_listener_rdv }
```

but the probelm is  under 
doctrine:
     orm:
            entity_listener_resolver: rendezvous_RendezVous.doctrine.rdv_entity_listener_resolver 
            entity_listener_resolver: instruction_Instruction.doctrine.entity_listener_resolver (is that correct ??)
plz help me and thank you

**Comment by kimhemsoe** [comment]
Sorry for the late response. Did you figure this out or?

**Comment by ahmedwafdi** [comment]
yeah i find the solution a long time ago :D thank i will post it here to close this issue

**Comment by ahmedwafdi** [comment]
here is the solution :)
```
services:

    ##Gestion des Notifications
    instruction_Instruction.doctrine.entity_listener_resolver:
        class: Instruction\InstructionBundle\Doctrine\EntityListenerResolver
        arguments: [ "@service_container" ]
        

    instruction_Instruction.entity_listener.instruction:
        class: Instruction\InstructionBundle\Listener\InstructionListener
        arguments: [ '@service_container' ]
        tags:
            -  { name: doctrine.entity_listener }
           
    ##Gestion des SMS & Email
    my.listener:
        class: RendezVous\RendezVousBundle\Listener\RendezVousListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }
            
    my.subscriber:
        class: RendezVous\RendezVousBundle\Listener\ListenerSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default } 
```

**Comment by ahmedwafdi** [comment]
here is the solution :)
```
services:

    ##Gestion des Notifications
    instruction_Instruction.doctrine.entity_listener_resolver:
        class: Instruction\InstructionBundle\Doctrine\EntityListenerResolver
        arguments: [ "@service_container" ]
        

    instruction_Instruction.entity_listener.instruction:
        class: Instruction\InstructionBundle\Listener\InstructionListener
        arguments: [ '@service_container' ]
        tags:
            -  { name: doctrine.entity_listener }
           
    ##Gestion des SMS & Email
    my.listener:
        class: RendezVous\RendezVousBundle\Listener\RendezVousListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }
            
    my.subscriber:
        class: RendezVous\RendezVousBundle\Listener\ListenerSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default } 
```
