### ISSUE TITLE
Creating Sqlite db fails because of quotes on path.

### ISSUE THREAD

**Issue by Armstrong1992** [doctrine/DoctrineBundle#482]
Hi, 
last release seems to break sqlite database creation with command.
In CreateDatabaseDoctrineCommand.php there is something strange :)

```php
 // Need to get rid of _every_ occurrence of dbname from connection configuration and we have already extracted all relevant info from url
unset($params['dbname'], $params['path'], $params['url']);
$tmpConnection = DriverManager::getConnection($params);
$shouldNotCreateDatabase = $ifNotExists && in_array($name, $tmpConnection->getSchemaManager()->listDatabases());
// Only quote if we don't have a path
if (!isset($params['path'])) {
    $name = $tmpConnection->getDatabasePlatform()->quoteSingleIdentifier($name);
}
```
 
unset($params['path']) and just few lines later if(!isset($params['path'])) results in 
```php
(line 58) Doctrine\DBAL\Schema\SqliteSchemaManagerarray:2 [
  "driver" => "pdo_sqlite"
  "path" => ""/var/www/bps/app/sqlite.db""
]
```
Config:
```yml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:  pdo_sqlite
                path:    %kernel.root_dir%/sqlite.db
                #memory: true
                charset: utf8
```
