### ISSUE TITLE
Resolve Target Entities are failing for OneToMany since version 1.6

### ISSUE THREAD

**Issue by trsteel88** [doctrine/DoctrineBundle#484]
I have a OneToMany target entity relationship:

``` yaml
Acme\DemoBundle\Model\Page:
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
...
    oneToMany:
        slugs:
            targetEntity: Acme\DemoBundle\Model\SlugInterface
            cascade:
                - remove
                - persist
            mappedBy: page
            inversedBy: null
            orphanRemoval: true
            orderBy: null
...
```

Since updating to 1.6, I now receive the following error:

```
Notice: Undefined index: Acme\DemoBundle\Model\SlugInterface
```

![screen shot 2015-11-06 at 7 42 14 am](https://cloud.githubusercontent.com/assets/869933/10982615/f1ec4e7c-8459-11e5-9f9c-4c7cba31a138.png)

Is anyone else having a similar issue?

**Comment by trsteel88** [comment]
Ok, I have found the commit that is causing the issue:

https://github.com/doctrine/DoctrineBundle/compare/d63be7eb9a95d46720f7d6badac4e5bc2bcff2e3...a5b3ba908ba68f3e14e42762a7b940fde65ed7da#diff-8f3578ddca2c59937b37c3331b2ab336L386

Can anyone explain what is going on here?

**Comment by trsteel88** [comment]
PR Here: #439

**Comment by KingCrunch** [comment]
Hi @trsteel88 

Did you miss to configure [`doctrine.orm.resolve_target_entity`](http://symfony.com/doc/current/cookbook/doctrine/resolve_target_entity.html) properly?

**Comment by trsteel88** [comment]
@KingCrunch, it is configured correctly.

```php
echo '<pre>';print_r($config['resolve_target_entities']);die;
```

```php
Array
(
    [Acme\DemoBundle\Model\SlugInterface] => Acme\DemoBundle\Model\Slug
)
```

I have an event listener that changes the model from a mappedSuperClass to an Entity. This allows me to override Models/Entities on a per project basis if required.

I don't know why your commit would change this behaviour though. It should still be functioning in the exact same way right?

It's like the events are no firing in a different order.

**Comment by trsteel88** [comment]
Ok, the issue is that the order of the events are now different. Subscribers fire first, then event listeners next. I think this is a big concern? I need my event listeners to fire before the EventSubscribers so it can change/build entities.

The only way I can resolve this within my application is to change my EventListeners to EventSubscribers.

As far as I can see, the Doctrine EventManager (or ContainerAwareEventManager) doesn't even use a priority attribute on tags.

**Comment by xabbuh** [comment]
@trsteel88 How did you try to configure the priority of your own listeners?

**Comment by trsteel88** [comment]
By setting a priority on the tag. I tried -100, 0, 100, 200. Regardless of the number, I wasn't able to move it around the new subscribe tag.

```yaml
    acme_demo.listener.service:
        class: Acme\DemoBundle\EventListener\SomeListener
        public: false
        tags:
            - { name: doctrine.event_listener, event: ***event_name***, priority: ***number*** }
```
