### ISSUE TITLE
Unknown database 'test'

### ISSUE THREAD

**Issue by Kvartir54** [doctrine/DoctrineBundle#521]
Hello, i have a problem.

It's my parameters.yml
```
parameters:
    database.driver: pdo_mysql
    database.host: 127.0.0.1
    database.name: test
    database.user: root
    database.password: null
```

it's my config.yml doctrine section
```
doctrine:
    dbal:
        default_connection: default

        connections:
            default:
                driver:   %database.driver%
                dbname:   %database.name%
                user:     %database.user%
                host:     %database.host%
                password: %database.password%
                charset:  UTF8
                server_version:       5.5.42
                e.t.c.
```

it's my composer.json and doctrine/dbal version
```
        "doctrine/orm": "~2.4,<2.5",
        "doctrine/dbal": "2.4.4",
        "doctrine/doctrine-bundle": "~1.5",
```

Now, when i run any command "app/console ...", i get this error:

> [PDOException]                                   
> SQLSTATE[HY000] [1049] Unknown database 'test'

Can anybody help me?
