### ISSUE TITLE
Undocumented hard dependency on Doctrine ORM

### ISSUE THREAD

**Issue by Ingannatore** [doctrine/DoctrineBundle#565]
I'm working on a Doctrine DBAL-only project and this is my composer's `require` block after removing the requirement for Doctrine ORM:

```json
{
    "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.8.*",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "^2.8",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "ramsey/uuid": "^3.0"
    }
}
```

After running `composer update`, I got the following error:

> PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Version" from namespace "Doctrine\ORM".

So I checked on [Packagist](https://packagist.org/packages/doctrine/doctrine-bundle) and in the `Requires` block I didn't find any reference to Doctrine ORM; nevertheless the class `Doctrine\Bundle\DoctrineBundle\DependencyInjection\DoctrineExtension` contains the following line

```php
use Doctrine\ORM\Version;
```

Am I missing something?

**Comment by stof** [comment]
It is not a hard dependency. It is a dependency of the bundle only in case you configure the ORM in your config. but it is perfectly fine to configure only the DBAL layer.

**Comment by Ingannatore** [comment]
I totally forgot to remove the `orm` block from my `config.yml`:

```yml
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
```

Thanks a lot @stof :)
