### ISSUE TITLE
Provide production-ready cache configuration with zero line config changes

### ISSUE THREAD

**Issue by Koc** [doctrine/DoctrineBundle#585]
As I understand correctly, Symfony 3.2 introduces production ready cache configuration out of the box. No need change anything in `config_prod.yml`: apcu included by default if it is installed with filesystem fallback, see https://github.com/symfony/symfony-standard/pull/974 . It would be nice if Doctrine Bundle also move in this direction.

// cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by stof** [comment]
We could do this for caches not needing to be shared. But several Doctrine caches must be shared (if you use a non-shared second level cache, you will have corrupted data all the time)

**Comment by weaverryan** [comment]
See https://github.com/symfony/symfony/issues/24545#issuecomment-336419270

I'm thinking about it quickly, but we should (as the code indicates) be able to add a new cache type for Doctrine that hooks into the `cache.system` service that everything else in Symfony uses. In fact, this would be a good example of how 3rd party bundles should cache things. The final config (for the user) could look something like:

```yml
# app/config/config_prod.yml
doctrine:
    orm:
        metadata_cache_driver: cache.system.doctrine_orm
        query_cache_driver: cache.system.doctrine_orm
#        result_cache_driver: apc
```

Where `cache.system.doctrine_orm` is some new service that DoctrineBundle provides that hooks into `system.cache`. We would still need `config_prod.yml`, because we would still want the `array` cache (i.e. no caching) for the dev environment. And as @stof mentioned, this would only be used by certain caches, I believe metadata & query make sense.
