### ISSUE TITLE
mapping annotations throws an exception

### ISSUE THREAD

**Issue by ghost** [doctrine/DoctrineBundle#59]
Using the latest master of doctrinebundle, I get the following exception

```
ServiceNotFoundException: The service "doctrine.orm.default_entity_manager" has a dependency on a non-existent service "annotation_reader".
```

When I specify a mapping as follows:

```
mappings:
    zikula_core_entities:
        type: annotation
        dir: %kernel.root_dir%/../src
        is_bundle: false
        prefix: Zikula
```
