### ISSUE TITLE
Integrate Embeddable for bundle mapping automatic configuration

### ISSUE THREAD

**Issue by Soullivaneuh** [doctrine/DoctrineBundle#594]
In order to have a well separated structure on my project, I want to put Embeddable classes on the `Embeddable` namespace, not `Entity`:

```php
namespace AppBundle\Embeddable;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Embeddable
 *
 * @author Sullivan Senechal <soullivaneuh@gmail.com>
 */
final class BillingRecipient
{
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $address;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $company;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $siret;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $nif;

    // Getters / Setters stuff...
}
```

And my mapping configuration, simple as hell:

```yaml
doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager:   default
        entity_managers:
            default:
                connection:           default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                default_repository_class: AppBundle\Repository\DefaultRepository
                mappings:
                    AppBundle: ~
```

But I got this error:

```
  [Doctrine\Common\Persistence\Mapping\MappingException]                                                                                                                                                                                                                 
  The class 'AppBundle\Embeddable\BillingRecipient' was not found in the chain configured namespaces AppBundle\Entity, Gedmo\Translatable\Entity, Gedmo\Translator\Entity, Gedmo\Loggable\Entity, Gedmo\Tree\Entity, FOS\OAuthServerBundle\Entity, FOS\UserBundle\Model  
```

This can be easily fixed with this configuration workaround

```yaml
doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager:   default
        entity_managers:
            default:
                connection:           default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                default_repository_class: AppBundle\Repository\DefaultRepository
                mappings:
                    AppBundle: ~
                    # We need to define the Embeddable folder manually
                    # because doctrine only looks at the Entity folder for automatic configuration.
                    AppBundle_embeddable:
                        type: annotation
                        dir: '%kernel.root_dir%/../src/AppBundle/Embeddable'
                        prefix: AppBundle\Embeddable
                        is_bundle: false
```

But I think this make sense to consider the `Embeddable` directory for the automatic configuration, and get rid of this trick.

What do you think?
