### ISSUE TITLE
Bundle configuration can use the sf expression language?

### ISSUE THREAD

**Issue by wdalmut** [doctrine/DoctrineBundle#613]
I have a simple question. The Doctrine bundle can use the expression language in order to have a flexible configuration?

```yml
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "@=service('app_configurator').getDatabaseHost()"
        ...
```

The `@=service...` is effectively passed as string to the library and not resolved by the expression language

```
[Doctrine\DBAL\Exception\ConnectionException]                                                                                   
An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known  
```

The `app_configurator` service is never created or called.

Is the expression language supported for the bundle configuration?
