### ISSUE TITLE
Schema generator is not adding COMMENT to custom type

### ISSUE THREAD

**Issue by fkrauthan** [doctrine/DoctrineBundle#618]
I am using the DoctrineEnumBundle and have a issue with the enum SQL that gets generated. It does not contain the COMMENT field which is required to identify the enum type correctly.

You can find a lot more information about this in the following two tickets:
* fre5h/DoctrineEnumBundle#87
* doctrine/dbal#2594

The versions in my `composer.json`:

```json
{
    "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.2.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6"
    }
}
```

Based on my lock file I am using

* Symfony: 3.2.3
* DoctrineORM: 2.5.6
* DoctrineBundle: 1.6.7

In addition to that my config.yml in regards of the custom type looks like this:

```yml
doctrine:
    dbal:
        #     ...
        types:
            FlowerState: AppBundle\DBAL\Type\FlowerStateType
            FlowerGraphicSetRarity: AppBundle\DBAL\Type\FlowerGraphicSetRarityType
            UserFlowerSort: AppBundle\DBAL\Type\UserFlowerSortType
```

As you can see on my last comment in the dbal ticket I found out that the [ConnectionFactory.php#L60](https://github.com/doctrine/DoctrineBundle/blob/master/ConnectionFactory.php#L60) might be the issue as it correctly detects that types as commented types but it never calls `markDoctrineTypeCommented` for them as `$mappingTypes` is empty.

I testwise moved that for loop that is guarded within the if condition below the if condition and the migration starts adding the comment to my custom enum fields.

Please help as this is very annoying that any DB migration I generate contains entries for my custom enum types to be converted back to string fields on the `down` method which if I forgot to delete would cause potential big issues if I ever have to roll back my migration.

Let me know if you need any more information.

**Comment by kimhemsoe** [comment]
@fkrauthan Is this still an issue?

**Comment by fkrauthan** [comment]
I haven't seen it lately but I also didn't add any new enums in a while. I guess we can close and in case I run into this again I will reopen a ticket.

**Comment by kirya-dev** [comment]
Problem SOLVED.
```yaml
doctrine:
    dbal:
        mapping_types:
            enum: string
        types:
            user_status_enum: App\Enum\UserStatusEnum
 ```
 
 ```php
 use Doctrine\DBAL\Types\Type;
 
 class UserStatusEnum extends Type
{
    public function getName(): string
    {
        return 'user_status_enum';
    }

    public function requiresSQLCommentHint(AbstractPlatform $platform): bool
    {
        return true;
    }
}
```
