### ISSUE TITLE
Non-bundle multiple mappings: container issue

### ISSUE THREAD

**Issue by maphe** [doctrine/DoctrineBundle#635]
I'm running with `1.6.7`.

Here is my orm config:

```yaml
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            user:
                dir: "%kernel.root_dir%/../src/AppBundle/Resources/config/doctrine/"
                type: yml
                prefix: User\Entity
                is_bundle: false
            api:
                dir: "%kernel.root_dir%/../src/AppBundle/Resources/config/doctrine/"
                type: yml
                prefix: Api\Entity
                is_bundle: false
```

I'm getting the following exception: `MappingException in MappingException.php line 75: No mapping file found named 'User.orm.yml' for class 'User\Entity\User'.`

Looking at the generated container cache (`\appDevDebugProjectContainer`):

```php
    protected function getDoctrine_Orm_DefaultEntityManagerService($lazyLoad = true)
    {
        $a = new \Doctrine\ORM\Mapping\Driver\SimplifiedYamlDriver(array(($this->targetDirs[3].'/src/AppBundle/Resources/config/doctrine') => 'Api\\Entity'));
        $a->setGlobalBasename('mapping');

        $b = new \Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain();
        $b->addDriver($a, 'User\\Entity');
        $b->addDriver($a, 'Api\\Entity');
        $b->addDriver(new \Doctrine\ORM\Mapping\Driver\XmlDriver(new \Doctrine\Common\Persistence\Mapping\Driver\SymfonyFileLocator(array(($this->targetDirs[3].'/vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping') => 'FOS\\UserBundle\\Model'), '.orm.xml')), 'FOS\\UserBundle\\Model');
...
```

Seems like only the last mapping has its driver initiated (tested switching the config). Editing manually, it fixes the issue:

```php
        $a2 = new \Doctrine\ORM\Mapping\Driver\SimplifiedYamlDriver(array(($this->targetDirs[3].'/src/AppBundle/Resources/config/doctrine') => 'User\\Entity')); // added
        $a2->setGlobalBasename('mapping'); // added

        $b->addDriver($a2, 'User\\Entity'); // edited
```
