### ISSUE TITLE
Multiple orm error

### ISSUE THREAD

**Issue by valetanddama** [doctrine/DoctrineBundle#687]
I have declare:

```yml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: UTF8
            custom:
                driver: pdo_mysql
                host: '%database_host_custom%'
                port: '%database_port_custom%'
                dbname: '%database_name_custom%'
                user: '%database_user_custom%'
                password: '%database_password_custom%'
                charset: UTF8
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    user:
                        type: annotation
                        dir: "%kernel.root_dir%/../src/AppBundle/Entity"
                        prefix: AppBundle\Entity
            custom:
                connection: custom
                mappings:
                    billing:
                        type: annotation
                        dir: "%kernel.root_dir%/../src/AppBundle/Billing/Entity"
                        prefix: AppBundle\Billing\Entity
```
Namespace in /src/AppBundle/Billing/Entity directory is AppBundle\Billing\Entity , but orm see classes from /src/AppBundle/Entity directory and can't see classes from /src/AppBundle/Billing/Entity.

> The class 'AppBundle\\Billing\\Entity\\Test' was not found in the chain configured namespaces AppBundle\\Entity, FOS\\UserBundle\\Model

What is the problem?
