### ISSUE TITLE
Phantom MySql Connection

### ISSUE THREAD

**Issue by JustBlackBird** [doctrine/DoctrineBundle#689]
I'm using `DoctrineBundle@1.6.7` and have the following config:

```
doctrine:
    dbal:
        default_connection: xxx
        connections:
            xxx:
                server_version: 9.4
                driver: "%database_driver%"
                host: "%database_host%"
                port: "%database_port%"
                dbname: "%database_name%"
                user: "%database_user%"
                password: "%database_password%"
                charset: UTF8
        types:
            foo:
                class: X\Y\Types\FooType # This is a commented type
```

Then I compile a container I have not only one connection but two: one `xxx` and another one is `default_connection`. The latter one has the following credentials:

```
driver: "pdo_mysql"
host: "localhost"
port: ~
user: root
password: ~
```

The main question is _where does the phantom connection come from?_
___
When I upgrade DoctrineBundle from `1.6.7` to `1.6.8` I get the same result as described in #673.

**Comment by JustBlackBird** [comment]
I've traced the problem a little and found a strange place in [`DependencyInjection\Configuration`](https://github.com/doctrine/DoctrineBundle/blob/master/DependencyInjection/Configuration.php#L69..L84)

This block is executed for `types` array which just cannot have `default_connection`
```
                        $v['default_connection'] = isset($v['default_connection']) ? (string) $v['default_connection'] : 'default';
                        $v['connections'] = array($v['default_connection'] => $connection);
```

**Comment by stof** [comment]
Can you run `bin/console debug:config doctrine` and post the output ?

**Comment by JustBlackBird** [comment]
Sure. Here it is:
```
doctrine:
    dbal:
        types:
            uuid:
                class: Ramsey\Uuid\Doctrine\UuidType
                commented: true
            binary_flag:
                class: SharedKernelBundle\Doctrine\BinaryFlagType
                commented: true
            numeric_id:
                class: SharedKernelBundle\Doctrine\NumericIdType
                commented: true
            year:
                class: SharedKernelBundle\Doctrine\YearType
                commented: true
            date_immutable:
                class: VasekPurchart\Doctrine\Type\DateTimeImmutable\DateImmutableType
                commented: true
            datetime_immutable:
                class: VasekPurchart\Doctrine\Type\DateTimeImmutable\DateTimeImmutableType
                commented: true
            datetimetz_immutable:
                class: VasekPurchart\Doctrine\Type\DateTimeImmutable\DateTimeTzImmutableType
                commented: true
            time_immutable:
                class: VasekPurchart\Doctrine\Type\DateTimeImmutable\TimeImmutableType
                commented: true
        default_connection: default
        connections:
            xxx:
                driver: pdo_mysql
                host: 'localhost'
                port: '3306'
                dbname: 'foo'
                user: 'bar'
                password: 'baz'
                schema_filter: /^sf_$/
                charset: UTF8
                logging: true
                profiling: true
                options: {  }
                mapping_types: {  }
                default_table_options: {  }
                slaves: {  }
                shards: {  }
            default:
                host: localhost
                port: null
                user: root
                password: null
                driver: pdo_mysql
                logging: true
                profiling: true
                options: {  }
                mapping_types: {  }
                default_table_options: {  }
                slaves: {  }
                shards: {  }
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: xxx
        entity_managers:
            xxx:
                connection: xxx
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    SharedKernelBundle:
                        type: annotation
                        dir: Domain
                        prefix: SharedKernelBundle\Domain
                        mapping: true
                    AppSecurityBundle:
                        type: annotation
                        dir: Domain
                        prefix: AppSecurityBundle\Domain
                        mapping: true
                query_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                metadata_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                result_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
                default_repository_class: Doctrine\ORM\EntityRepository
                auto_mapping: false
                quote_strategy: doctrine.orm.quote_strategy.default
                entity_listener_resolver: null
                repository_factory: null
                hydrators: {  }
                filters: {  }
        proxy_dir: /home/app/var/cache/dev/doctrine/orm/Proxies
        proxy_namespace: Proxies
        resolve_target_entities: {  }
```

And here is a part of my `config.yml`:

```
doctrine:
    dbal:
        types:
            uuid:
                class: Ramsey\Uuid\Doctrine\UuidType
                commented: true
            binary_flag:
                class: SharedKernelBundle\Doctrine\BinaryFlagType
                commented: true
            numeric_id:
                class: SharedKernelBundle\Doctrine\NumericIdType
                commented: true
            year:
                class: SharedKernelBundle\Doctrine\YearType
                commented: true

        default_connection: xxx
        connections:
            xxx:
                driver: pdo_mysql
                host: "localhost"
                port: "3306"
                dbname: "foo"
                user: "bar"
                password: "baz"
                schema_filter: "/^sf_$/"
                charset: UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: xxx
        entity_managers:
            xxx:
                connection: xxx
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    SharedKernelBundle:
                        type: annotation
                        dir: Domain
                        prefix: SharedKernelBundle\Domain
                    AppSecurityBundle:
                        type: annotation
                        dir: Domain
                        prefix: AppSecurityBundle\Domain
```

The most interesting thing is `default_connection` option is different from one I've wrote down in the config.

**Comment by stof** [comment]
Do you have a config for the `doctrine` key in another config file in your project, which may be the source of the second connection ?

And then, if the answer is no, look for usage of `Container::prependExtensionConfig` usage in the whole project (including dependencies as it might come from a third-party bundle) with `doctrine` as extension.

**Comment by JustBlackBird** [comment]
The only config that include `doctrine` key is `config_test.yml`:

```
doctrine:
    dbal:
        connections:
            xxx:
                driver: pdo_sqlite
                path: "%kernel.cache_dir%/test.db"
                user: ~
                password: ~
                schema_filter: "/.*/"
```

As far as I can see there is no usage of `prependExtensionConfig` neither in the project nor in the dependencies.
