### ISSUE TITLE
DBAL query result cache configuration

### ISSUE THREAD

**Issue by dmaicher** [doctrine/DoctrineBundle#737]
If I have this config:

```yaml
doctrine:
    orm:
        entity_managers:
            default:
                result_cache_driver:
                    type: service
                    id: cache.memcache
```

And somewhere retrieve the default dbal connection to perform a cached query like

```php
$connection->executeCacheQuery(
    'SELECT ...',
    [],
    [],
    new QueryCacheProfile(360)
);
```

I get this error:

```
Doctrine\DBAL\Cache\CacheException:
Trying to cache a query but no result driver is configured.

  at vendor/doctrine/dbal/lib/Doctrine/DBAL/Cache/CacheException.php:41
  at Doctrine\DBAL\Cache\CacheException::noResultDriverConfigured()
     (vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:943)
```
Should the ORM config not also apply for DBAL? Or do I need to configure this manually somehow?
