### ISSUE TITLE
SF4 Missing column types?

### ISSUE THREAD

**Issue by rikvanderkemp** [doctrine/DoctrineBundle#743]
Installed a fresh version of Symfony 4, added the doctrine bundles via `composer req doctrine`.

Afterwards I created a new entity and tried `./bin/console doctrine:schema:update`. I now have several column types (of which none are in annotated properties) that Doctrine wants to see mapped. 

These are, so far:

- money
- config_object

So I tried mapping 'money' to DecimalType and that works. But I have no idea where to map config_object and somehow I think this will lead to another missing column type.

The following is currently installed:

```
doctrine/annotations                v1.5.0             
doctrine/cache                      v1.7.1             
doctrine/collections                v1.5.0             
doctrine/common                     v2.8.1             
doctrine/dbal                       v2.6.3             
doctrine/doctrine-bundle            1.8.1              
doctrine/doctrine-cache-bundle      1.3.2              
doctrine/doctrine-migrations-bundle v1.3.1             
doctrine/inflector                  v1.2.0             
doctrine/instantiator               1.1.0              
doctrine/lexer                      v1.0.1             
doctrine/migrations                 v1.6.2             
doctrine/orm                        dev-master f13f7eb 
jdorn/sql-formatter                 v1.2.17            
ocramius/package-versions           1.2.0              
ocramius/proxy-manager              2.1.1              
psr/cache                           1.0.1              
psr/container                       1.0.0              
psr/log                             1.0.2              
psr/simple-cache                    1.0.0              
sensio/framework-extra-bundle       dev-master 28792a4 
symfony/cache                       v4.0.0             
symfony/config                      v4.0.0             
symfony/console                     v4.0.0             
symfony/debug                       v4.0.0             
symfony/dependency-injection        v4.0.0             
symfony/doctrine-bridge             v4.0.0             
symfony/dotenv                      v4.0.0             
symfony/event-dispatcher            v4.0.0             
symfony/filesystem                  v4.0.0             
symfony/finder                      v4.0.0             
symfony/flex                        v1.0.44
symfony/framework-bundle            v4.0.0             
symfony/http-foundation             v4.0.0             
symfony/http-kernel                 v4.0.0             
symfony/lts                         dev-master 396c5fc 
symfony/maker-bundle                dev-master 6137fe1
symfony/orm-pack                    v1.0.4             
symfony/polyfill-mbstring           v1.6.0             
symfony/process                     v4.0.0             
symfony/routing                     v4.0.0             
symfony/web-server-bundle           v4.0.0             
symfony/yaml                        v4.0.0             
zendframework/zend-code             3.3.0              
zendframework/zend-eventmanager     3.2.0              
```

My doctrine.yaml is fairly standard, except for the obvious money type mapping:

```
parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'
        types:
          money: \Doctrine\DBAL\Types\DecimalType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```
