### ISSUE TITLE
Fatal Error: auto_generate_proxy_classes default value 

### ISSUE THREAD

**Issue by rsaenen** [doctrine/DoctrineBundle#761]
Hi,
After `composer update`, I got Fatal Error caused by doctrine which don't find proxy classes on prod mode.

I had the following configuration with Symfony 4 and Flex lastest version:
```yml
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```

After an update, I got the following error:
```bash
2018-01-18T18:46:02.385271+00:00 app[web.1]: [2018-01-18 18:46:02] php.WARNING: Warning: require(/app/var/cache/prod/doctrine/orm/Proxies/__CG__AppEntityProfile.php): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): Warning: require(/app/var/cache/prod/doctrine/orm/Proxies/__CG__AppEntityProfile.php): failed to open stream: No such file or directory at /app/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php:223)"} []
2018-01-18T18:46:02.386436+00:00 app[web.1]: [2018-01-18 18:46:02] php.CRITICAL: Fatal Compile Error: require(): Failed opening required '/app/var/cache/prod/doctrine/orm/Proxies/__CG__AppEntityProfile.php' (include_path='.:/app/.heroku/php/lib/php') {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: require(): Failed opening required '/app/var/cache/prod/doctrine/orm/Proxies/__CG__AppEntityProfile.php' (include_path='.:/app/.heroku/php/lib/php') at /app/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php:223)"} []
```

I switch the value of `auto_generate_proxy_classes` to `true` and don't get any errors.

It seems legit that I had an error with ` auto_generate_proxy_classes: '%kernel.debug%' (false in prod mode)` but I can't figure out why it works before the update.
