### ISSUE TITLE
Shouldn't default_table_options be inherited from the database?

### ISSUE THREAD

**Issue by tvlooy** [doctrine/DoctrineBundle#766]
Consider this configuration:

```
doctrine:
    dbal:
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
```

Shouldn't I be able to leave out the ```default_table_options```? It seems like the charset can be inherited from the database?
