### ISSUE TITLE
Can't configure mapping when I use many database connections

### ISSUE THREAD

**Issue by fadoe** [doctrine/DoctrineBundle#784]
I have a application with many database connections. For one connection I defined some mapping types. My doctrine configuration:

```yaml
doctrine:
    dbal:
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                mapping_types:
                    station_id: "Namespace\\Doctrine\\Type\\StationIdType"
                    external_station_id: "Namespace\\Doctrine\\Type\\ExternalStationIdType"
         # other connections are here
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            manager_name:
                connection: default
                mappings:
                    NamespaceEntity:
                        dir: "%kernel.project_dir%/app/config/mappings/namespace"
                        is_bundle: false
                        type: xml
                        prefix: Namespace\\Entity
``` 
When I load the entity with the station_id type, I get this exception:

```
Type to be overwritten Namespace\Doctrine\Type\StationIdType does not exist.
```
When I debug, doctrine only knows his standard types. The namespace is found by my application, otherwise the entity would not be found.

I can't find a documentation for this, only when mapping enum to string. So my question: Have i missconfigured something or is this a bug?

**Comment by fadoe** [comment]
Okay, I found the error:

```yaml
doctrine:
    dbal:
        types:
            station_id: "Namespace\\Doctrine\\Type\\StationIdType"
            external_station_id: "Namespace\\Doctrine\\Type\\ExternalStationIdType"
```
