### ISSUE TITLE
Recommended approach for disabling the logging in some occurrences

### ISSUE THREAD

**Issue by tzfrs** [doctrine/DoctrineBundle#787]
Hello,

in some parts of the code, we are importing data from an API. Because this can be very heavy, we currently just disable the `SQLLogger` of doctrine like this

```php
$emConfig = $this->entityManager->getConnection()->getConfiguration();
// Temporarily save the logger so it can be reused later.
$sqlLogger = $emConfig->getSQLLogger();
$emConfig->setSQLLogger(null);

// Do the import/write to the db, blabla

$emConfig->setSQLLogger($sqlLogger);
```

Now, we're doing this for all our Importers and now thought of doing things kinda different. First thought was to just define a new connection, set `logging` to `false`, define a new entity manager and use the new entity manager (instead of the default one) in our services.

This works, however we now have duplicate configuration in the `config.yml`, which makes the `dbal` part look like this

```yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: "%database_driver%"
                host: "%database_host%"
                port: "%database_port%"
                dbname: "%database_name%"
                server_version: "%database_version%"
                user: "%database_user%"
                password: "%database_password%"
                charset: UTF8
            import:
                driver: "%database_driver%"
                host: "%database_host%"
                port: "%database_port%"
                dbname: "%database_name%"
                server_version: "%database_version%"
                user: "%database_user%"
                password: "%database_password%"
                charset: UTF8
                logging: false
```

As you can see, these both connections are both exactly the same and the only diff is that the `import` connection has `logging` set to false. This is the same case for defining the `entity_managers` in the `orm` section. They mostly have the exact same configuration and only difference is the `connection` and `auto_mapping` part.

Now, there are multiple ways to achieve what we're doing

1. By PHP as we're doing it now.
2. By configuration, defining all services to the fullest, like in the example above
3. By configuration, writing a custom `CompilerPass` which creates a second `EntityManager` with `logging` set to false, but otherwise exactly the same as the `default` entity manager.

Before approaching this problem by code, I wanted to ask if there's a recommended way to achieve what we're achieving, i.e. how the maintainers/contributors of this project would handle such a case.

I couldn't find any info on this in the documentation, because it seems like it's not a common use case to have exactly the same entity_managers/connections with minor differences.

The reason I'm asking is, because the main idea was to separate the connection configuration from the business logic without having an overhead on configuration.
