### ISSUE TITLE
Undefined `default` connection gets added or defined `default` connection get their credentials overwritten

### ISSUE THREAD

**Issue by c33s** [doctrine/DoctrineBundle#811]
using `doctrine/doctrine-bundle` version `1.8.1` i run into the error stated below. on the dev server everything works like charm (prod and dev env) but if i deploy the app to the prod server or a vagrant linux machine i get the following error:

```
An exception occured while establishing a connection to figure out your platform version.
You can circumvent this by setting a 'server_version' configuration value

For further information have a look at:
https://github.com/doctrine/DoctrineBundle/issues/673

In AbstractMySQLDriver.php line 121:

An exception occurred in driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'


In PDOConnection.php line 47:

SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'


In PDOConnection.php line 43:

SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'
```
which leads me to the issue https://github.com/doctrine/DoctrineBundle/issues/673

not sure if the error described applies to my case, because i defined the `server_version` also i have valid credentials in the doctrine settings. 

```
doctrine:
    dbal:
        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType
        connections:
            default_connection: app
            app:
                driver:         pdo_mysql
                #url:            '%env(resolve:DATABASE_URL)%'
                url:            'mysql://user:password@127.0.0.1:3306/db'
                server_version: '5.5'
                charset:        utf8mb4
            legacy:
                driver:         pdo_mysql
                #url:            '%env(resolve:DATABASE_URL_LEGACY)%'
                url:            'mysql://user_legacy:password_legacy@127.0.0.1:3306/db_legacy'
                server_version: '5.5'
                charset:        utf8mb4
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: app
        entity_managers:
            app:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                connection: app
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            legacy:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: false
                connection: legacy
                mappings:
                    Legacy:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Legacy/Entity'
                        prefix: 'App\Legacy\Entity'
                        alias: Legacy

```
first i thought it is because of missing env variables, so i enabled the console to use the `.env` file, then i tried to move the config values directly in the `doctrine.yaml`. all with no effort.

i don't understand i get this error  although i defined the server version, also i don't under

dev machine: `mysql  Ver 15.1 Distrib 10.1.13-MariaDB, for Win64 (AMD64)`
prod machine: `mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

is this a bug or is my config simply wrong?

if i dump the config:
`php bin/console debug:config doctrine --env=dev`
```
doctrine:
    dbal:
        types:
            uuid:
                class: Ramsey\Uuid\Doctrine\UuidType
                commented: true
            money:
                class: Tbbc\MoneyBundle\Type\MoneyType
                commented: true
        default_connection: default
        connections:
            default:
                host: localhost
                port: null
                user: root
                password: null
                driver: pdo_mysql
                logging: true
                profiling: true
                options: {  }
                mapping_types: {  }
                default_table_options: {  }
                slaves: {  }
                shards: {  }
            app:
                driver: pdo_mysql
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '5.5'
                charset: utf8mb4
                host: localhost
                port: null
                user: root
                password: null
                logging: true
                profiling: true
                options: {  }
                mapping_types: {  }
                default_table_options: {  }
                slaves: {  }
                shards: {  }
            legacy:
                driver: pdo_mysql
                url: '%env(resolve:DATABASE_URL_LEGACY)%'
                server_version: '5.5'
                charset: utf8mb4
                host: localhost
                port: null
                user: root
                password: null
                logging: true
                profiling: true
                options: {  }
                mapping_types: {  }
                default_table_options: {  }
                slaves: {  }
                shards: {  }
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: app
        entity_managers:
            app:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                connection: app
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: /home/.../site/app/src/Entity
                        prefix: App\Entity
                        alias: App
                        mapping: true
                query_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                metadata_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                result_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
                default_repository_class: Doctrine\ORM\EntityRepository
                quote_strategy: doctrine.orm.quote_strategy.default
                entity_listener_resolver: null
                repository_factory: doctrine.orm.container_repository_factory
                hydrators: {  }
                filters: {  }
            legacy:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: false
                connection: legacy
                mappings:
                    Legacy:
                        is_bundle: false
                        type: annotation
                        dir: /home/.../site/app/src/Legacy/Entity
                        prefix: App\Legacy\Entity
                        alias: Legacy
                        mapping: true
                query_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                metadata_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                result_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
                default_repository_class: Doctrine\ORM\EntityRepository
                quote_strategy: doctrine.orm.quote_strategy.default
                entity_listener_resolver: null
                repository_factory: doctrine.orm.container_repository_factory
                hydrators: {  }
                filters: {  }
        proxy_dir: /home/.../site/app/var/cache/dev/doctrine/orm/Proxies
        proxy_namespace: Proxies
        resolve_target_entities: {  }
```

`php bin/console debug:config doctrine --env=prod`

```
doctrine:
    dbal:
        types:
            uuid:
                class: Ramsey\Uuid\Doctrine\UuidType
                commented: true
            money:
                class: Tbbc\MoneyBundle\Type\MoneyType
                commented: true
        default_connection: default
        connections:
            default:
                host: localhost
                port: null
                user: root
                password: null
                driver: pdo_mysql
                logging: false
                profiling: false
                options: {  }
                mapping_types: {  }
                default_table_options: {  }
                slaves: {  }
                shards: {  }
            app:
                driver: pdo_mysql
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '5.5'
                charset: utf8mb4
                host: localhost
                port: null
                user: root
                password: null
                logging: false
                profiling: false
                options: {  }
                mapping_types: {  }
                default_table_options: {  }
                slaves: {  }
                shards: {  }
            legacy:
                driver: pdo_mysql
                url: '%env(resolve:DATABASE_URL_LEGACY)%'
                server_version: '5.5'
                charset: utf8mb4
                host: localhost
                port: null
                user: root
                password: null
                logging: false
                profiling: false
                options: {  }
                mapping_types: {  }
                default_table_options: {  }
                slaves: {  }
                shards: {  }
    orm:
        auto_generate_proxy_classes: false
        default_entity_manager: app
        entity_managers:
            app:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                connection: app
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: /home/.../site/app/src/Entity
                        prefix: App\Entity
                        alias: App
                        mapping: true
                query_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                metadata_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                result_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
                default_repository_class: Doctrine\ORM\EntityRepository
                quote_strategy: doctrine.orm.quote_strategy.default
                entity_listener_resolver: null
                repository_factory: doctrine.orm.container_repository_factory
                hydrators: {  }
                filters: {  }
            legacy:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: false
                connection: legacy
                mappings:
                    Legacy:
                        is_bundle: false
                        type: annotation
                        dir: /home/.../site/app/src/Legacy/Entity
                        prefix: App\Legacy\Entity
                        alias: Legacy
                        mapping: true
                query_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                metadata_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                result_cache_driver:
                    type: array
                    namespace: null
                    cache_provider: null
                class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
                default_repository_class: Doctrine\ORM\EntityRepository
                quote_strategy: doctrine.orm.quote_strategy.default
                entity_listener_resolver: null
                repository_factory: doctrine.orm.container_repository_factory
                hydrators: {  }
                filters: {  }
        proxy_dir: /home/.../site/app/var/cache/prod/doctrine/orm/Proxies
        proxy_namespace: Proxies
        resolve_target_entities: {  }
```

the "wrong" default connection is added in all envs and on the prod and dev server. even if i rename the connection `app` to `default` the credentials get overwritten.

**Comment by weaverryan** [comment]
Hey @c33s!

Yes, that `default` connection is definitely your problem. The question is, why is it being added? I would check VERY closely to make sure you don't have a `doctrine` key in ANY other config file. My guess is that you DO, and the config from that file is being merged with this file. I especially think this is true because when you run `debug:config doctrine`, I see both a custom `UuidType` and `MoneyType`. But, in your posted config, you only have `UuidType`. I bet that the extra `MoneyType` is coming from the same config file that's giving your the default type.

Anyways, closing as this is more of a support question - it's not an issue. You can ask these questions on the Symfony Slack channel, or Stack Overflow.

Cheers!

**Comment by c33s** [comment]
@weaverryan thank you for your fast reply, yes it is a problem with the multiple config files/flex, i fixed it by moving the doctrine type configs from the  packages to the global doctrine config but i think it is more than a stackoverflow question, it is more of a bug or at least bad DX.

`packages/ramsey_uuid_doctrine.yaml`
```
doctrine:
    dbal:
        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType
```
interferes with `services.yaml`
```
doctrine:
    dbal:
        types:
            money: Tbbc\MoneyBundle\Type\MoneyType
        connections:
            default_connection: app
            app:
                driver:         pdo_mysql
                #url:            '%env(resolve:DATABASE_URL)%'
                url:            'mysql://user:password@127.0.0.1:3306/db'
                server_version: '5.5'
                charset:        utf8mb4
            legacy:
                driver:         pdo_mysql
                #url:            '%env(resolve:DATABASE_URL_LEGACY)%'
                url:            'mysql://user_legacy:password_legacy@127.0.0.1:3306/db_legacy'
                server_version: '5.5'
                charset:        utf8mb4
```

i would assume that the type defined in `ramsey_uuid_doctrine.yaml` cleanly gets merged with my doctrine config in `services.yaml` and that i don't have to remove the `type` part from `packages/ramsey_uuid_doctrine.yaml` and add it to `services.yaml`. also i would assume that it behaves similar in dev and in prod / windows and linux.

maybe it is more a config component or a flex issue, at least the documentation for doctrine multiple connections should be updated and a warning should be added there.
