### ISSUE TITLE
ORM config merging adds the 'default' entity manager

### ISSUE THREAD

**Issue by xgrn** [doctrine/DoctrineBundle#816]
Hello.

I have a yaml bundle configuration file with entity manager definitions like the following.

```yaml
doctrine:
    orm:
        entity_managers:
            manager1:
                connection: conn1
            manager2:
                connection: conn2
```
Another configuration file is used on the production to change cache drivers only so it's loaded separately.
```yaml
doctrine:
    orm:
        metadata_cache_driver:
            type: service
            id: doctrine.system_cache_provider
        query_cache_driver:
            type: service
            id: doctrine.system_cache_provider
        result_cache_driver:
            type: service
            id: doctrine.result_cache_provider
```
The Symfony configuration processor normalises each configuration before merging it. At the same time the Doctrine bundle configuration looks for an 'entity_manager(s)' section in each ORM section and adds a 'default' entity manager otherwise.

As a result the 'default' manager with default configuration is added to the second config than merged.

At the end I have 3 entity managers: 'manager1', 'manager2' and 'default' instead of 2.

Later in the code I set up some filters for each manager at the runtime. As the 'default' manager has an empty configuration and no filters configured the application crashes.

I use a workaround like
```php
if($name === 'default') return;
```
before filter setup but it doesn't look as a clean code.

Best wishes.

**Comment by pluk77** [comment]
I found a similar issue, which related to the default_entity_manager setting, which is disregarded in the prod environment if it is not specifically set in the doctrine.yml for prod.

here is the issue I logged: https://github.com/symfony/symfony/issues/27769

**Comment by stof** [comment]
your prod config uses a shortcut notation to configure the entity manager, which is configuring an entity manager named `default`. If you use multiple entity managers, you will need to update the file configure the prod caches for the entity managers, to configure your 2 entity managers instead.

**Comment by pluk77** [comment]
That does still does not explain why the "default_entity_manager" setting is completely ignored.

**Comment by stof** [comment]
In the config you gave above, there is no configuration for `default_entity_manager` at all. So I don't see which config is ignored according to you.

**Comment by pluk77** [comment]
I am not sure if this is the right place to comment, as my issue might be slightly different to the original issue reported here and I do not want to hijack it.

I am referring to the configs I gave in this issue:

symfony/symfony#27769

In there, the default_entity_manager is ignored.

**Comment by xgrn** [comment]
@stof my issue may be the same as the @pluk77 issue. At least it has the same root. The problem is the following.

We have 2 doctrine.yml: the common one and the environment specific (prod in my case).

```yaml
doctrine.yml

doctrine:
    orm:
        entity_managers:
            manager1:
                connection: connection1
            manager2:
                connection: connection2
```

```yaml
prod/doctrine.yml

doctrine:
    orm:
        query_cache_driver:
            type: service
            id: doctrine.system_cache_provider
```

Now we load them in the MyKernel::configureContainer. The configuration loader takes each file and _normalises them separately_ before merging. Normalisation calls the sequence described in doctrine-bundle/DependencyInjection/Configuration.php The following code does the magic (Configuration::addOrmSection).

```php
doctrine-bundle/DependencyInjection/Configuration.php

->beforeNormalization()
    ->ifTrue(function ($v) {
        return $v === null || (is_array($v) && ! array_key_exists('entity_managers', $v) && ! array_key_exists('entity_manager', $v));
    })
    ->then(function ($v) {
        $v = (array) $v;
        // Key that should not be rewritten to the connection config
        $excludedKeys  = [
            'default_entity_manager' => true,
        'auto_generate_proxy_classes' => true,
            'proxy_dir' => true,
        'proxy_namespace' => true,
        'resolve_target_entities' => true,
            'resolve_target_entity' => true,
        ];
        $entityManager = [];
        foreach ($v as $key => $value) {
            if (isset($excludedKeys[$key])) {
                continue;
            }
            $entityManager[$key] = $v[$key];
            unset($v[$key]);
        }
        $v['default_entity_manager'] = isset($v['default_entity_manager']) ? (string) $v['default_entity_manager'] : 'default';
        $v['entity_managers']        = [$v['default_entity_manager'] => $entityManager];

        return $v;
    })
->end()
```

For the first yaml (doctrine.yml) the 'ifTrue' condition is FALSE as the ORM section contains the 'entity_managers' section. As for the second file (prod/doctrine.yml) it's TRUE as this file doesn't contain entity manages. So the 'beforeNormalization' handler is triggered and these two lines:

```php
$v['default_entity_manager'] = isset($v['default_entity_manager']) ? (string) $v['default_entity_manager'] : 'default';
$v['entity_managers']        = [$v['default_entity_manager'] => $entityManager];
```

...add the 'default' entity manager. So the final configuration looks like this.

```yaml
doctrine:
    orm:
        entity_managers:
            default_entity_manager: default
            manager1:
                connection: connection1
            manager2:
                connection: connection2
            default:
                query_cache_driver:
                    type: service
                    id: doctrine.system_cache_provider
```

The correct way I found is to put the cache configuration into the prod config as the following.

```yaml
prod/doctrine.yml

doctrine:
    orm:
        entity_managers:
            manager1:
                connection: connection1
                query_cache_driver:
                    type: service
                    id: doctrine.system_cache_provider
            manager2:
                connection: connection2
                query_cache_driver:
                    type: service
                    id: doctrine.system_cache_provider
```

The issue may be closed here I believe (as it's my config is wrong in fact). I'd say this behaviour with adding the default entity manager may be just unexpected.

Cheers!
