### ISSUE TITLE
Unknown "profiler_dump" function in "DoctrineBundle:Collector:db.html.twig" 

### ISSUE THREAD

**Issue by KopiasCsaba** [doctrine/DoctrineBundle#824]
Hi all!

I would like to request to update this piece of code that is mentioned in the log below:

> [2018-05-29 14:40:41] assetic.ERROR: The template "DoctrineBundle:Collector:db.html.twig" contains an error: Unknown "profiler_dump" function in "DoctrineBundle:Collector:db.html.twig" at line 241. [] []

As it raises errors at us!

Thank you very much, and thank you for doctrine bundle.

**Comment by magikid** [comment]
Just came to say that this bug bit us in the butt this morning.  When trying to deploy out our site with debug off in our prod environment, our site was throwing a ton of exceptions with the message "Lexer or parser ended up in unsupported state".  The root cause was tracked down to this function which is undefined in our prod environment.

My work around was to create a bundle that is only loaded in prod that defines this function in a Twig extension service.  The `profiler_debug` function that this service defines is an empty function.

**Comment by alcaeus** [comment]
This looks like it could be related to https://github.com/symfony/symfony/issues/19039 - can you please check the suggestions there?

**Comment by magikid** [comment]
Their solution is to list out all bundles with twig templates in them.  That's not really a great solution when you have around 200 bundles (not including vendors like DoctrineBundle) which may or may not contain twig templates.

**Comment by alcaeus** [comment]
From what I can tell this isn’t a problem with DoctrineBundle: it’s assetic loading a Template file that it shouldn’t load. Configuring assetic appropriately will fix that problem.

**Comment by magikid** [comment]
While I think assetic is part of the problem, this bundle is the only one that throws this error so I wonder if there's not some configuration that could happen here to resolve that as well.

**Comment by alcaeus** [comment]
I have no idea. Your best bet is to check the assetic or Symfony support channels for help with this. IIRC, Symfony no longer recommends using assetic, so I'm not sure how much help you'll receive in their support channels. If there is something we can change to make this work, I'll gladly merge a PR.

**Comment by ostrolucky** [comment]
Agreed, this isn't doctrine bundle issue. Remove DoctrineBundle from your assetic configuration:
```yml
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - AppBundle
        - EverlutionFileBundle
        - EverlutionImportBundle
        - EverlutionSearchBundle
        - NelmioApiDocBundle
        - JMSJobQueueBundle
        - HttplugBundle
```

Let's close @alcaeus ?
