### ISSUE TITLE
Overriding xml mappings file ignored

### ISSUE THREAD

**Issue by danaki** [doctrine/DoctrineBundle#846]
I'm trying to override a field from an external bundle by using an approach similar to the one [described here](https://jmspaymentcorebundle.readthedocs.io/en/stable/guides/overriding_entity_mapping.html).

In my project I want to override the type of recipientId field from [this mapping](https://github.com/yokai-php/messenger-bundle/blob/master/Resources/config/model/Notification.orm.xml). My doctrine config looks like following:
```
doctrine:
    dbal:
        # ...
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Money:
                is_bundle: false
                type: xml
                prefix: Money
                dir: '%kernel.project_dir%/config/doctrine/Money'
            YokaiMessengerBundle:
                is_bundle: false                
                type: xml
                prefix: Yokai\MessengerBundle\Entity
                dir: '%kernel.project_dir%/config/doctrine/YokaiMessengerBundle'
```

I've created a new file to override mappings and put it in config/doctrine/YokaiMessengerBundle/Notification.orm.xml

The reason why I do not provide it contents is because contents are ignored, about any text, even invalid XML is ignored. Of course if I put there
```
<field name="recipientId"    column="recipient_id"    type="string"   nullable="false" length="255"/>
```
it's ignored too.

Am I missing something?
