### ISSUE TITLE
Doctrine event subscriber config location

### ISSUE THREAD

**Issue by lolmx** [doctrine/DoctrineBundle#859]
Hello everyone,

I encountered a weird bug yesterday where one of my doctrine event subscriber was not called.

I'm using doctrine-bundle 1.9.1, orm 2.6.2, along with symfony 3.4.15 (reproduced with 3.4.16 too).

After some debugging i found why, but i can't understand it.

Long story short, if a doctrine event subscriber is declared in `services.yml`, no problem, but if i declare it in a separate config file (which is imported by `services.yml`) then it is completely ignored.

Any reason, or is this a bug?

This can be easily reproduced:
`composer create-project symfony/framework-standard-edition my_project_name "3.4.*"`

Create an entity
```php
/**
 * @ORM\...
 */
class Dummy
{
    /**
     * @ORM\Id()
     * ...
     */
    private $id;

    /**
     * @ORM\Column()
     */
    private $filled;

    /**
     * @ORM\Column()
     */
    private $notFilled;

    // getters & setters
}
```

Create two doctrine subscribers
```php
class Called implements EventSubscriber
{
    public function getSubscribedEvents()
    {
        return [
            Events::prePersist,
        ];
    }

    public function prePersist(LifecycleEventArgs $args)
    {
        $entity = $args->getObject();

        if (!$entity instanceof Dummy) {
            return;
        }

        $entity->setFilled('yes!");
    }
}
```
```php
class NotCalled implements EventSubscriber
{
    public function getSubscribedEvents()
    {
        return [
            Events::prePersist,
        ];
    }

    public function prePersist(LifecycleEventArgs $args)
    {
        $entity = $args->getObject();

        if (!$entity instanceof Dummy) {
            return;
        }

        $entity->setNotFilled('No :(");
    }
}
```

```yaml
# services.yml
imports:
    - { resource: name.yml }

services:
    # ...
    Namespace\To\Called:
        tags:
            - { name: doctrine.event_subscriber }
```
```yaml
# name.yml
services:
    # ...
    Namespace\To\NotCalled:
        tags:
            - { name: doctrine.event_subscriber }
```

And here a test class
```php
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DummyTest extends WebTestCase
{
    public function testBothSubscribersShouldBeCalled()
    {
        $kernel = static::bootKernel($options);
        $entityManager = $kernel->getContainer()->get('doctrine.orm.default_entity_manager');

        $dummy = new Dummy();
        $entityManager->persist($dummy);
        $entityManager->flush(); // will throw exception because the column not_filled is null
    }
}
```

If needed i can provide those classes in a working example.

**Comment by xabbuh** [comment]
What is the output of `bin/console debug:container 'Namespace\To\NotCalled'`?

**Comment by lolmx** [comment]
Hello,
Thanks for your interest!
Here's the output of the command
```
Information for Service "Namespace\To\NotCalled"
==================================================================

 ---------------- ------------------------------------------ 
  Option           Value                                     
 ---------------- ------------------------------------------ 
  Service ID       Namespace\To\NotCalled  
  Class            Namespace\To\NotCalled  
  Tags             -                                         
  Public           no                                        
  Synthetic        no                                        
  Lazy             no                                        
  Shared           yes                                       
  Abstract         no                                        
  Autowired        yes                                       
  Autoconfigured   yes                                       
 ---------------- ------------------------------------------ 
```
We see here that there are no tags, but we did specify one in the config file.

**Comment by xabbuh** [comment]
You probably have a PSR-4 based service locator config in your other `services.yml` file that overrides the one you expect to be loaded.

**Comment by lolmx** [comment]
I don't understand what you mean with 'a PSR-4 based service locator config'.

I'm using the default symfony autowiring in both files
```yaml
# services.yml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    # ...
```

And i also tried to set the autoconfiguration to false

```yaml
# name.yml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Namespace\To\NotCalled:
        autoconfigure: false
        tags:
            - { name: doctrine.event_subscriber }
```

**Comment by xabbuh** [comment]
I meant that you have something like this: https://symfony.com/doc/current/service_container.html#importing-many-services-at-once-with-resource

If having this overlapping services defined in the imported file they will overwrite each other.

**Comment by lolmx** [comment]
Indeed the problem was that import.

After excluding the directory where the subscriber lives in it works well.
```yml
# services.yml
# ...
    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Directory/of/Subscriber}'
```
I was not aware that this could override previous defined services. I thought it would take user-defined services first, but i was wrong.

Anyways, thank you very much for your help!
