### ISSUE TITLE
MSSQL driver support `FormatDecimal` parameter.

### ISSUE THREAD

**Issue by Jeeppler** [doctrine/DoctrineBundle#893]
By default the official Microsoft MSSQL driver omits leading zeros for decimal and money types. That means, MSSQL returns .00 instead of 0.00. 

There is already an issue, which discusses this behaviour: https://github.com/Microsoft/msphpsql/issues/415 and more importantly there is already a [preview release v5.5.0-preview](https://github.com/Microsoft/msphpsql/releases/tag/v5.5.0-preview) which allows to change this behaviour. 

Microsoft added several [configuration parameters](https://github.com/Microsoft/msphpsql/wiki/Features#formatDecimals) to the MSSQL driver, which allow to influence the behaviour on per query and a general connection level.

On connection level the behaviour can be changed by setting `FormatDecimal` to `true`. I tried to set the value in a Symfony 3 application using a connection string:

```
doctrine:
    dbal:
      url: "sqlsrv://user:password@host:port/database_name?FormatDecimals=true"
```

and by using the `option` section:

```
doctrine:
    dbal:
        driver: 'sqlsrv'
        host: "%database.host%"
        dbname: "%database.name%"
        user: "%database.user%"
        password: "%database.password%"
        port: "%database.port%"
        options:
          FormatDecimals: true
```

However, non of the options worked. Either, I did a mistake or the `FormatDecimals` option has to be added to the DoctrineBundle and maybe even to Doctrine ORM in general.
