### ISSUE TITLE
MSSQL driver support `FormatDecimal` parameter

### ISSUE THREAD

**Issue by Jeeppler** [doctrine/DoctrineBundle#894]
By default the official Microsoft MSSQL driver omits leading zeros for decimal and money types. That means, MSSQL returns .00 instead of 0.00. 

There is already an issue, which discusses this behaviour: https://github.com/Microsoft/msphpsql/issues/415 and more importantly there is already a [preview release v5.5.0-preview](https://github.com/Microsoft/msphpsql/releases/tag/v5.5.0-preview) which allows to change this behaviour. 

Microsoft added several [configuration parameters](https://github.com/Microsoft/msphpsql/wiki/Features#formatDecimals) to the MSSQL driver, which allow to influence the behaviour on per query and a general connection level.

On connection level the behaviour can be changed by setting `FormatDecimal` to `true`. I tried to set the value in a Symfony 3 application using a connection string:

```
doctrine:
    dbal:
      url: "sqlsrv://user:password@host:port/database_name?FormatDecimals=true"
```

and by using the `option` section:

```
doctrine:
    dbal:
        driver: 'sqlsrv'
        host: "%database.host%"
        dbname: "%database.name%"
        user: "%database.user%"
        password: "%database.password%"
        port: "%database.port%"
        options:
          FormatDecimals: true
```

However, non of the options worked. Either, I did a mistake or the `FormatDecimals` option has to be added to the DoctrineBundle and maybe even to Doctrine ORM in general.

**Comment by Jeeppler** [comment]
@kimhemsoe is there anything I can do to help?

**Comment by Jeeppler** [comment]
Any update on this issue?

**Comment by stof** [comment]
The PDO option is `PDO::SQLSRV_ATTR_FORMAT_DECIMALS` according to the doc you linked. A this constant is probably an integer as value, and not the `FormatDecimals` string.

**Comment by Jeeppler** [comment]
@stof thanks for the response. However, I still do not understand how to configure the `PDO::SQLSRV_ATTR_FORMAT_DECIMALS` in the DoctrineBundle.  I am more than happy to give any suggestion a try.

**Comment by Jeeppler** [comment]
Microsoft released driver version 5.6 to production: [Production Release for the PHP drivers Version 5.6.0 for SQL Server](https://github.com/Microsoft/msphpsql/releases/tag/v5.6.0). The new driver supports the decimal parameter.

**Comment by alcaeus** [comment]
Sorry for the delay here. Options need to use the corresponding `PDO` constant as key. In your case, the value of the constant is `1007`, thus your config should look like this:
```yaml
    dbal:
      connections:
        default:
          driver: 'sqlsrv'
          host: "%database.host%"
          dbname: "%database.name%"
          user: "%database.user%"
          password: "%database.password%"
          port: "%database.port%"
          options:
            1007: true
```

Please let me know if that works for you.

**Comment by bert126** [comment]
I am fighting with the same issue and neither 1007 nor FormatDecimals seems to work. 

I am already using SqlSrv 5.6 and DBAL 2.9.x

Is ‘options’ the correct name for passing this parameter? I thought it was ‘driverOptions’ as described in the documentation here : 

https://www.doctrine-project.org/projects/doctrine-dbal/en/2.9/reference/configuration.html

Thank you for your help.

**Comment by Jeeppler** [comment]
@bert126 have you tried using `driverOptions` instead of `options`?

**Comment by alcaeus** [comment]
@Jeeppler did it work for you using `driverOptions` or `options`?

**Comment by Jeeppler** [comment]
@alcaeus I never tried any solution. I am unable to tell you if it works or not.

**Comment by bert126** [comment]
> @Jeeppler did it work for you using `driverOptions` or `options`?

I just tested it right now and I get the solution.

It's working perfectly with `driverOptions` (but not with `options`). And you should use the constant  `1007 ` (and not `FormatDecimals`).

I can now have `decimal` fields declared under Ms-Sql Server, and I declare them properly as `decimal` in Doctrine annotations.

This piece of code is then working (PHP).

```
        $connectionOptions = array(
            'driver' => 'pdo_sqlsrv',
            'user' => 'xxx',
            'password' => 'xxx',
            'host' => 'xxx',
            'dbname' => 'xxx',
            'driverOptions' => array(
                '1007'=>true,
            )
        );
```

**Comment by alcaeus** [comment]
Thanks for confirming, @bert126! Closing as solved.

**Comment by Jeeppler** [comment]
I tried it today with a `yaml` configuration. The following code works:

```
# Doctrine Configuration
doctrine:
    dbal:
        driver: 'pdo_sqlsrv'
        host: "%database.host%"
        dbname: "%database.name%"
        user: "%database.user%"
        password: "%database.password%"
        port: "%database.port%"
        options:
          1007: true  # Format decimal values with leading zeros
```
