### ISSUE TITLE
Still an issue: Class Doctrine\Common\Proxy\AbstractProxyFactory does not exist

### ISSUE THREAD

**Issue by lbayerl** [doctrine/DoctrineBundle#908]
The issue mentioned [here](https://github.com/symfony/symfony/issues/29390) and to my understanding should have been fixed with version 1.10.1 with [this merge](https://github.com/doctrine/DoctrineBundle/pull/881) still seems to exist for me.

After using composer ```create-project symfony/skeleton myproject``` and ```composer require doctrine/doctrine-bundle``` it installs 1.10.1 of the Doctrine bundle but I still receive the following error message:

> In BaseNode.php line 422:
> Invalid configuration for path "doctrine.orm.auto_generate_proxy_classes": Class Doctrine\Common\Proxy\AbstractProxyFactory does not exist

> In Configuration.php line 714:
> Class Doctrine\Common\Proxy\AbstractProxyFactory does not exist

**Comment by SenseException** [comment]
Thank you. Did you take a look if the mentioned fix hasn't covered this bug completely or if this has another cause? Can you please contribute a failing test that reproduces this error?

**Comment by Majkl578** [comment]
Can you please post your configuration for Doctrine bundle (the `doctrine:` section)?

The Symfony recipe for this bundle naively assumes you will also use ORM and adds default section: https://github.com/symfony/recipes/blob/481ce0a9f1619c0bea95d1b37c4477a9880f7039/doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml#L19
So you need this to be deleted, with only `dbal:` left.

**Comment by barell** [comment]
I just had the same issue described here. This is my doctrine configuration generated by recipe:

```
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```

To resolve, I had to manually run `composer require doctrine/orm`
