### ISSUE TITLE
onFlush events with 2 or more dbal connections throw ErrorExceptions

### ISSUE THREAD

**Issue by trooney** [doctrine/DoctrineBundle#93]
Using Symfony 2.1 BETA. In configuration's with 2 connections, onFlush events written to `(appDevDebugProject|appProd)Container.php` contain calls to addEventListener. The method signature for the 2nd connection is incorrect. Changing the order the connection's are specified produces the incorrect signature on whatever happens to be the 2nd connection.

Compare the signatures for MysqlConnectionService and PlatConnectionService:

`appDevDebugProjectContainer.php`

``` php
protected function getDoctrine_Dbal_MysqlConnectionService()
{
    $c->addEventListener(array(0 => 'onFlush'), $this->get('nrc_notice.notice.notice_listener'));
}


protected function getDoctrine_Dbal_PlatConnectionService()
{
    $c->addEventListener(array(0 => array(0 => 'onFlush')), $this->get('nrc_notice.notice.notice_listener'));
}
```

Error Message

``` text
ErrorException: Warning: Illegal offset type in /Applications/MAMP/htdocs/checknet.local/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php line 115

in /Applications/MAMP/htdocs/checknet.local/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php line 115
at ErrorHandler->handle('2', 'Illegal offset type', '/Applications/MAMP/htdocs/checknet.local/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php', '115', array('events' => array(array('onFlush')), 'listener' => object(NoticeListener), 'hash' => '000000000bfa891500000000295a660c', 'event' => array('onFlush'))) in /Applications/MAMP/htdocs/checknet.local/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php line 115
at ContainerAwareEventManager->addEventListener(array(array('onFlush')), object(NoticeListener)) in /Applications/MAMP/htdocs/checknet.local/app/cache/dev/appDevDebugProjectContainer.php line 272
at appDevDebugProjectContainer->getDoctrine_Dbal_PlatConnectionService() in /Applications/MAMP/htdocs/checknet.local/app/bootstrap.php.cache line 194
at Container->get('doctrine.dbal.plat_connection') in /Applications/MAMP/htdocs/checknet.local/app/cache/dev/appDevDebugProjectContainer.php line 370
at appDevDebugProjectContainer->getDoctrine_Orm_PlatEntityManagerService() in /Applications/MAMP/htdocs/checknet.local/app/bootstrap.php.cache line 194
at Container->get('doctrine.orm.plat_entity_manager') in /Applications/MAMP/htdocs/checknet.local/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ManagerRegistry.php line 35
```

My `config.yml`

``` yml
doctrine:
    dbal:
        default_connection: mysql
        connections:
            mysql:
                 driver: etc...
            plat:
                 driver_class:   etc...
```

My `services.yml`

``` yml
services:
  nrc_notice.notice.notice_listener:
     class: Some\Listener\Class
     arguments:
       container: '@service_container'
     tags:
        - { name: kernel.event_listener, event: nrc_notice.notice.change.approved, method: onNotify }
```

Similar pattern occurs while adding more connections:

``` php

protected function getDoctrine_Dbal_MysqlConnectionService()
{
    $c->addEventListener(array(0 => 'onFlush'), $this->get('nrc_notice.notice.notice_listener'));
}

protected function getDoctrine_Dbal_Mysql2ConnectionService()
{
    $c->addEventListener(array(0 => array(0 => 'onFlush')), $this->get('nrc_notice.notice.notice_listener'));
}

protected function getDoctrine_Dbal_PlatConnectionService()
{
    $c->addEventListener(array(0 => array(0 => array(0 => 'onFlush'))), $this->get('nrc_notice.notice.notice_listener'));
}
```
