### ISSUE TITLE
Better cache mapping

### ISSUE THREAD

**Issue by guilhermeblanco** [doctrine/DoctrineBundle#97]
Currently, if you use a non-default cache support, like Redis, you're forced to map 3 instances for a single entity manager.
To simplify this support, and also make #65 and also remove the need of http://knpbundles.com/search?q=cache, we could use the 2.2 CacheBundle support ( https://github.com/symfony/symfony/pull/3225 ) or simplify this by allowing our own cache:

```
doctrine:
    cache:
        apc: ~
    orm:
        // ...
        metadata_cache_driver: apc
```

This would also allow people to retrieve the cache drivers from service container.
