### ISSUE TITLE
[1.11] schema_filter configuration no longer works

### ISSUE THREAD

**Issue by enumag** [doctrine/DoctrineBundle#971]
We have some Doctrine entities which are read only because they are mapped to views instead of regular tables. To prevent the tables from being generated by doctrine migrations we're using a configuration like this:

```yaml
doctrine:
    dbal:
        schema_filter: ~^(?!foo_view|bar_view)~
```

After updating to DoctrineBundle 1.11.1 this no longer works and doctrine/migrations is trying to generate normal tables for these entities.
