### ISSUE TITLE
Entity "App\Entity\Product" not configured as part of the second-level cache. using redis cache

### ISSUE THREAD

**Issue by adityarai** [doctrine/DoctrineBundle#974]
@ORM\Cache(usage="READ_ONLY", region="one_day") in Product Entity

Doctrine configuration:

```yaml
doctrine:
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        second_level_cache:
            enabled: true
            region_cache_driver: redis
            regions:
                one_day:
                    lifetime: 86400 # 1 day
                    cache_driver: redis
        metadata_cache_driver: redis
        result_cache_driver: redis
        query_cache_driver: `redis`
```

In Symfony 4.2, error occurs when setCacheable(true) is added in createQueryBuilder

return $this->createQueryBuilder('fs')->setCacheable(true)->getQuery()->getArrayResult();

Error:
Entity "App\Entity\Product" not configured as part of the second-level cache at vendor/doctrine/orm/lib/Doctrine/ORM/Cache/CacheException.php:60
  at Doctrine\ORM\Cache\CacheException::nonCacheableEntity('App\\Entity\\Product')
     (vendor/doctrine/orm/lib/Doctrine/ORM/Cache/DefaultQueryCache.php:271)
  at Doctrine\ORM\Cache\DefaultQueryCache->put(object(QueryCacheKey), object(ResultSetMapping),
